### ISSUE TITLE
Couple of keys not producing sounds

### ISSUE THREAD

**Issue by tysonflint** [hainguyents13/mechvibes#1]
I downloaded "Mechvibes.Setup.1.0.2.exe" and didn't run it, but rather unzipped it using 7Zip, then went to the $pluginsdir and unzipped "app-64.7z".  From the unzipped sub-folder, I ran "Mechvibes.exe", which appears to run just fine without needing to run the installer.

I'm noticing that my letter U key is the only letter that does not produce a sound.

I also notice that my  num-lock numbers do not produce sounds when the num-lock is active (but do produce sounds when num-lock is disabled,.  For example Home/PgUp/PgDown on the num-pad produce sounds.

Is is required to run the installer to get full functionality.  I'd like to be able to run this a a "portable" app if possible.

Thank you,

-=Tyson

**Comment by hainguyents13** [comment]
Hey Tyson,
thanks for trying this app and letting me know your experience, it's actually a portable app, the installer just do the copy/paste job.

The problem with the letter U key is a bug, I just found it myself last night, but thank you anyway, I just fixed and committed the code, there will be no longer this bug in next release.

About some keys not producing sounds, I intended to record all the sounds of a TKL layout keyboard, not a full-size keyboard, because some of the keyboards that I own not in full-size but TKL layout.

I will include the zipped only version in the next release, and it will be available soon!

Thanks for your valuable feedback!

**Comment by timeakesmarky** [comment]
I also need the portable version of this app. Thanks. :)

**Comment by hainguyents13** [comment]
I just uploaded a new version of Mechvibes, including 8 sets of sound, and the portable zipped version.

**Comment by andika207** [comment]
it doesn't support XP. what a shame. !

**Comment by hainguyents13** [comment]
> it doesn't support XP. what a shame. !

my bad!

**Comment by andika207** [comment]
10 days later. you have released another version but it only supports the dead W7

**Comment by hainguyents13** [comment]
> 10 days later. you have released another version but it only supports the dead W7
of course, it supports Windows 7 and later, Windows XP is outdated and will never be supported.
Really sorry!

**Comment by andika207** [comment]
@hainguyents13  
XP has been receiving official updates till April 2019. 
some web browsers for XP get weekly updated
there are some projects such as core API in the works to get new apps to run on XP
Russia's president and other important companies are still on XP.
does it require NET 4.5 ?

**Comment by hainguyents13** [comment]
> @hainguyents13
> XP has been receiving official updates till April 2019.
> some web browsers for XP get weekly updated
> there are some projects such as core API in the works to get new apps to run on XP
> Russia's president and other important companies are still on XP.
> does it require NET 4.5 ?

If you really want to run this app on WinXP, please provide error detail and your PC specs

**Comment by andika207** [comment]
**@hainguyents13**
there is no error detail,  just a little window show up and says ''W7 or later are needed''
with other apps when they don't support XP you get the typical error window ''it's not a valid Win32 application''
with other apps you can also see different errors on startup but they end up working fine.

PC specs ? ASUS mainboard(s) and AMD or intel quadcore 
(XP is only an issue to find USB or graphic drivers on very recent hardware)

When a tool doesn't run on XP I test it on another PC with W7  to see wether it's worth keeping it.
I found your utility really nice to me this is why I'm trying to convince you to backport it to XP.

I found out your app in this site from India
https://www.thewindowsclub.com/mechvibes-play-mechanical-key-press-sound
