### ISSUE TITLE
Doesn't work on Administrator programs

### ISSUE THREAD

**Issue by max-programming** [hainguyents13/mechvibes#10]
Very nice and great app. I just love using it. But it does not work on apps that we run as administrator.
Video with audio on imgur.
https://imgur.com/jOkVJ1P

I tried it in PowerShell admin but it did not work

**Comment by hainguyents13** [comment]
If you run Powershell as admin, you should run Mechvibes as admin too

**Comment by max-programming** [comment]
ohkay. Got it. Thanks!

**Comment by hainguyents13** [comment]
@max-programming hey thanks for sharing it, I'm learning Electron too, it's the first time I use Electron for my project so it is not very optimized, but I glad it helps you somehow. If there is any suggestion, just let me know!

**Comment by max-programming** [comment]
Yeah. That is great. I am trying to build an audio recorder in Electron. I have run into a problem, Maybe you can help me pls? https://stackoverflow.com/questions/62022233/recording-and-saving-audio-file-becomes-weird
