### ISSUE TITLE
Returns Error message Whenn Executing It

### ISSUE THREAD

**Issue by HeflerDev** [hainguyents13/mechvibes#102]
Ubuntu 20.04

`/snap/mechvibes/1/resources/electron.asar/renderer/init.js:166 Unable to load preload script: /snap/mechvibes/1/resources/app.asar/src/preload.js`

`/snap/mechvibes/1/resources/electron.asar/renderer/init.js:167 Error: libxkbcommon-x11.so.0: cannot open shared object file: No such file or directory`

**Comment by ShukinDmitriy** [comment]
i got a similar error. packages libxkbcommon-x11-0 and libxkbcommon0 are installed. any ideas how to fix this?
