### ISSUE TITLE
Nie chce się włączyć

### ISSUE THREAD

**Issue by UHCmurzyn** [hainguyents13/mechvibes#107]
Włączam program i cały czas pisze loading... zostawiłem na 8h i dalej się nie załadowało co mam zrobić żeby działało komputer do ustawień fabrycznych restartowałem i mam tylko ten program na kompie i dalej to samo

**Comment by LordkaHakeroska** [comment]
A jaki masz system?

**Comment by UHCmurzyn** [comment]
windows 10


śr., 28 lip 2021 o 07:31 LordkaHakeroska ***@***.***>
napisał(a):

**Comment by NotLazy** [comment]
#250
