### ISSUE TITLE
Some keys not working with an azerty keyboard

### ISSUE THREAD

**Issue by LightShaft** [hainguyents13/mechvibes#108]
Hello.

I've got an azerty keyboard (french layout) and some keys do not make any sound, no matter the soundpack.
The Mechvibes logo do press tho, meaning it detects the key is being registered. When I take a look at the editor, I don't see a way for me to edit the soundpack myself to produce a sound when I press those keys.

So basically, I'm asking if it's possible to have other layouts support.
![image](https://user-images.githubusercontent.com/27209225/124791762-a396a700-df4c-11eb-939f-d44428f322c9.png)
Also the fn key on my keyboard doesn't work at all and it's not even pressed on the Mechvibes logo but I guess that's because it can't be detected as it's meant for combos

Thanks a lot

**Comment by hainguyents13** [comment]
Hi there,
maybe your layout is not very popular, I don't  know what is it's keycode
so I cannot assign any sound to it. I will try to dig more about
other layouts and update the app soon!
About the fn key, yeah fn key is a special key that doesnt fire any event
when pressed, so there is nothing I can do about it. Sorry for that.
