### ISSUE TITLE
VALORANT and Mechvibes

### ISSUE THREAD

**Issue by Fate28k** [hainguyents13/mechvibes#110]
When I play VALORANT, my Mechvibes switches are not making any noises, and I have tried to redownload VALORANT and everything, but nothing still. Yet, it works with any other game that is not Riot-related. How do I fix this issue?

**Comment by SerialKillah** [comment]
> When I play VALORANT, my Mechvibes switches are not making any noises, and I have tried to redownload VALORANT and everything, but nothing still. Yet, it works with any other game that is not Riot-related. How do I fix this issue?

Reinstall hall mechvibes , and when u download it make it "Run as adminstration" Then dont turn on auto startup
