### ISSUE TITLE
Long pressing 2 or more keys at the same time wont stop making a sound

### ISSUE THREAD

**Issue by SkidTamer** [hainguyents13/mechvibes#111]
When I press 2 or more keys at the same time, they just keep making a sound. I don't do this on purpose but sometimes when im playing competitive fps games this happens. Can you add a fix to it thanks :))

**Comment by kopa-github** [comment]
So basically what happens to me, it's when you press and hold a button to type out the same letter multiple times, there is always a short delay, and the sound appears at the same time as that delay (as if someone pressed the key one more time) although you don't press anything, you hold. So when the spam starts is when the sound plays basically. I can post a video if I wasn't clear enough.

**Comment by kopa-github** [comment]
But long pressing 2 keys at the same time will also produce the spam issue except it will continue to play sound for each letter instead of just at the start of the spam. It's very annoying and kind of sounds like a gun fire. It would be very distracting in games, especially FPS shooters.
