### ISSUE TITLE
Mechvibes in valorant

### ISSUE THREAD

**Issue by SerialKillah** [hainguyents13/mechvibes#112]
Mechvibes works , when i open my valorant it doesn't sound anymore?

**Comment by DznDani** [comment]
try running it with admin privileges

**Comment by MessiahHamilton** [comment]
How do i run admin privileges on my ubuntu os

**Comment by val8119** [comment]
> How do i run admin privileges on my ubuntu os

run it with `sudo <command>`

**Comment by AspectOfJerry** [comment]
Duplicate of #110
