### ISSUE TITLE
Enable at Startup in Windows

### ISSUE THREAD

**Issue by Sam071100** [hainguyents13/mechvibes#113]
After deselecting 'enable at startup' options and quitting mechvibes and after again restarting mechvibes the option is enabled automatically. It is not remembering my preferences and always starting up whenever I start Windows which looks irritating.
What is the command that should be entered in config.json of mechvibes to disable 'enable at startup' permanently?

**Comment by MuhammadMkm17** [comment]
I also have the same problem. Uninstalling and reinstalling the application doesn't solve the problem. @hainguyents13 Please help us😅
