### ISSUE TITLE
Delay on keyboard sounds (MacOS)

### ISSUE THREAD

**Issue by rheachi** [hainguyents13/mechvibes#12]
After not touching/using the keyboard for about a minute, the sounds become delayed for a moment then go back to normal. Not a major issue, but a little annoying to be honest. This is for MacOS, haven't tried this on windows yet. I'll give an update later.

**Comment by hainguyents13** [comment]
delay after a long idle time is the problem of all of the apps which work with keyboard and mouse events like Mechvibes, the "garbage collection" system will free up audio data from your memory if you dont use it for a while. 

The bright side is Mechvibes has the shortest delay time compared to other apps that I have tested :)

However, I will try my best to prevent this from happening again.

**Comment by rheachi** [comment]
Cool. I hope you can find a solution. Great work btw!

**Comment by ghoomfrog** [comment]
@hainguyents13 I'm still experiencing this so I guess it can't ever be fixed?

**Comment by NotLazy** [comment]
@ghoomfrog I'm still investigating solutions to the problem.

**Comment by Kamek437** [comment]
You rock man keep up the good work.

**Comment by RendyPakeY** [comment]
has anyone found a solution?
this still happened until now
