### ISSUE TITLE
Mac M1 Support

### ISSUE THREAD

**Issue by tappydrive** [hainguyents13/mechvibes#134]
Seems to be not working well on M1 Mac. sounds are delayed and are not synchronising well

**Comment by vpat-git** [comment]
App does not work at all for me on M1

**Comment by mihai-bica** [comment]
Works good on macbook air m1 for me. No bigger delays than on windows 10.

**Comment by arga1234** [comment]
App does not work at all for me on M1

**Comment by NotLazy** [comment]
The app works for me on M1 Pro, without issues. Ensure you've installed rosetta so you can run x64 apps on arm. As for delayed sounds, thats a duplicate of #13
