### ISSUE TITLE
great program but not minimize automatically on reboot

### ISSUE THREAD

**Issue by niceman882** [hainguyents13/mechvibes#136]
I have tried version No 2.3.0. and the program is really great and works fine with me , I would really like to thank the designer of this program for this idea.
But I have a problem that I hope you will take into mind in the next versions, which is that the program does not automatically minimize the window when the computer starts, and this is really annoying because I need to close it manually every time. Thank you

**Comment by iammursalin** [comment]
+1
I came here to say that too.
A big thanks to the developer who created it.
But it would be great if you guys add the auto minimize to tray option without popping up on the screen.
Thanks again for this program.

**Comment by Z1xus** [comment]
yes! that's what we need! i love this app, but it's annoying when after every reboot it's opening and you need manually minimize it to tray

**Comment by NotLazy** [comment]
dupe #55 #169
