### ISSUE TITLE
Something Wrong With My MechVibe

### ISSUE THREAD

**Issue by remyrancic** [hainguyents13/mechvibes#137]
Hi there,
My cousin was playing with my laptop a month back and suddenly my mechvibes are not working. I tried everything including reinstalling and unstalling it but nothing works. I hope you can help me with this issue as this software actually gives me comfort while I'm doing my Masters Research. Please email me as soon as you can as it is very awkward now to type in silence and without the sound of the beautiful keyboard clicks that you have made. I am reachable at
**remyrancic@gmail.com**
I hope to have a feed back from you soon. 
Sincerely,
Remy Rancic

![Screenshot 2021-11-15 020422](https://user-images.githubusercontent.com/94313886/141693019-6da85368-56fb-43ae-bf25-3a5b46b01d83.jpg)

**Comment by ohdxno** [comment]
same thing happened to me

**Comment by ThatNoobYeetR** [comment]
same thing happened to me

**Comment by blackgoddemon** [comment]
same did you find any solution

**Comment by NotLazy** [comment]
Fixed in #250
