### ISSUE TITLE
whats wrong with my mechvibes (im on mac)

### ISSUE THREAD

**Issue by ohdxno** [hainguyents13/mechvibes#138]
I was using mechvibes, (it was working normally), and nothing out of the ordinary happened. Around 15-20 minutes later, I realized it wasn't loading (the mechvibes window was blank, there were no options, just a white screen). So then I deleted mechvibes and downloaded it again and when I opened it, it didn't have any switch options. It was just blank. I tried quitting and reopening it again and again and nothing happened. What should I do to fix this?
<img width="400" alt="Screen Shot 2021-11-23 at 10 24 22" src="https://user-images.githubusercontent.com/94882998/142969093-a1297f80-8474-4c3f-9fcb-8eddc9d14154.png">
?\

**Comment by P-DennyGamingYT** [comment]
System Preferences > Privacy > Check Mechvibes then restart.

**Comment by NotLazy** [comment]
Fixed by #250
