### ISSUE TITLE
Loading except sound pack options not working

### ISSUE THREAD

**Issue by HababyAvocado** [hainguyents13/mechvibes#139]
Before I click sound options:
![image](https://user-images.githubusercontent.com/78855638/143485586-bd9e7de3-3de9-49d3-a746-f5789563b725.png)

After I click sound options

![image](https://user-images.githubusercontent.com/78855638/143485594-7ae4064c-bbad-435c-9c63-66f93ef358ef.png)

**Comment by HababyAvocado** [comment]
Notice the yellow stuff in the after  I click sound options picture

**Comment by ZebZeb69** [comment]
in the folder , . . . the one you go to when you click "custom folder"
it can **only** contain :     other folders  that contain the wav's, oggs, config, etc..
If you have an empty or other sub folder in it,
that is when it will only show up as blank.
also, remember to always quit & restart the program after every custom folder change, 
so it will see the new folders on startup.

**Comment by NotLazy** [comment]
Fixed by #250
