### ISSUE TITLE
suspended in standby state

### ISSUE THREAD

**Issue by HELLSNAKES** [hainguyents13/mechvibes#141]
![](https://cdn.discordapp.com/attachments/822128081736302623/916118216080769074/unknown.png)

**Comment by P-DennyGamingYT** [comment]
Same, IDK how to fix. I am on Windows tho.

**Comment by P-DennyGamingYT** [comment]
Windows: Install [Visual C++](https://aka.ms/vs/16/release/vc_redist.x64.exe). Then re-open Mechvibes.

MacOS: System Preferences > Privacy > Mechvibes and enable. Then re-open Mechvibes.
