### ISSUE TITLE
Mechvibes SRC, how to make it an app?

### ISSUE THREAD

**Issue by P-DennyGamingYT** [hainguyents13/mechvibes#143]
Hi, I download the src and it is in HTML and I was wondering how you tuned it into an app. Because I just put a web browser in a Windows Forms App but that didn't work. If you could help me that would be great!

My discord: https://discord.com/users/79093428563

**Comment by P-DennyGamingYT** [comment]
If you want to you can just DM me on Discord about it.

**Comment by BearTS** [comment]
Bruh @P-DennyGamingYT Literally the scripts are there 
![image](https://user-images.githubusercontent.com/65192718/155527359-7f031c96-6734-4e66-9c5b-0873c7ffb652.png)
Refer to that 
Need to have node js installed

**Comment by snakeboy105DG** [comment]
bruh beeeb beeeeeeeeeeeeeeeeeeeeeeeeeeebbbbbbduechwefycagwefy

**Comment by snakeboy105DG** [comment]
fvfvfv

**Comment by BearTS** [comment]
@snakeboy105DG  ??
