### ISSUE TITLE
custom folder issues

### ISSUE THREAD

**Issue by ZebZeb69** [hainguyents13/mechvibes#144]
in the folder , . . . the one you go to when you click "custom folder"
it can  _* only *_  contain : other folders that contain the wav's, oggs, config, etc..
If you have an empty or other sub folder in it,
that is when it will only show up as blank.
also, remember to always quit & restart the program after every custom folder change,
so it will see the new folders on startup.

**Comment by NotLazy** [comment]
Fixed by #250
