### ISSUE TITLE
sound only play after a few second when playing mc

### ISSUE THREAD

**Issue by manisricefrumsrt** [hainguyents13/mechvibes#145]

**Comment by manisricefrumsrt** [comment]
so when i play mc,the sound would have a delay tme of 2-5 seconds and i dont know why its happening pls help me.

**Comment by manisricefrumsrt** [comment]
and just in case this helps,it does lagg alot too

**Comment by P-DennyGamingYT** [comment]
This is probably due to your lack of computing power available on your PC. Maybe try having only MC open when playing.

**Comment by manisricefrumsrt** [comment]
> This is probably due to your lack of computing power available on your PC. Maybe try having only MC open when playing.

thx it dosent have delay issiues now

**Comment by manisricefrumsrt** [comment]
.
