### ISSUE TITLE
Keydown / Keyup sound

### ISSUE THREAD

**Issue by ainyava** [hainguyents13/mechvibes#146]
Hello, great app
I think it would be better to hear separate sounds for keydown/keyup events
Like when user hold the button down s/he don't hear keyup sound until really release the button.
Thanks

**Comment by Mohsin-Ul-Islam** [comment]
Can I contribute by working on this? I would love to implement this feature. @hainguyents13 @ainyava

**Comment by NoEnd-yt** [comment]
I would find this feature amazing!

**Comment by writeblankspace** [comment]
I think Mechvibes++ has this. Not on linux nor mac tho

**Comment by NoEnd-yt** [comment]
Yes I'm on Linux that's why

**Comment by NoEnd-yt** [comment]
Don't really care anymore since I got my hands on a real mechanical keyboard.

**Comment by NotLazy** [comment]
#21
