### ISSUE TITLE
Website down?

### ISSUE THREAD

**Issue by ItsK1tty** [hainguyents13/mechvibes#152]
https://mechvibes.com appears to be down. Is this intentional?

**Comment by Hoaper** [comment]
> https://mechvibes.com appears to be down. Is this intentional?

Yup, also this issue

**Comment by hainguyents13** [comment]
sorry guys, Vutrl just delete my server and create a new blank one, now the website is gone. Im trying to redirect it to a new one

**Comment by Hoaper** [comment]
Cool! Please dot not forgot to add ssl certificate to avoid "Not secure connection" from browsers

**Comment by max-programming** [comment]
> sorry guys, Vutrl just delete my server and create a new blank one, now the website is gone. Im trying to redirect it to a new one

What is the new address?
