### ISSUE TITLE
choose the Output device 

### ISSUE THREAD

**Issue by ahmedthebest31** [hainguyents13/mechvibes#16]
can you allow us to choose the Output device to play the keybord sound 
  i want to use another outbot device not my speekers

**Comment by NotLazy** [comment]
Unfortunately, I don't think this is possible with electron.

**Comment by vsviridov** [comment]
https://github.com/electron/electron/issues/13771 Looks like there's an API for that.

**Comment by NotLazy** [comment]
> https://github.com/electron/electron/issues/13771 Looks like there's an API for that.

Looks like that API might not work with our audio wrapper, and also is "experimental" but I'll continue to look into this when I get to my desk.
