### ISSUE TITLE
recommendation

### ISSUE THREAD

**Issue by the-devGuy** [hainguyents13/mechvibes#160]
Hi!

I'm a user of Mechvibes, and I really like it! I looked on the README, and it said that all ideas are welcome. So here are two of mine:
1. Extend this for the mouse. I want to use this for making Keyboard and Mouse ASMR Videos, so it would be really cool if you could do that.
2. When you press a key, the sound that is played is the sound of a key being pressed and then immediately. However on a real keyboard, a sounds comes out when you press it, and when you release it. It would be nice if that would be integrated

Thanks, 
the-devGuy

**Comment by NotLazy** [comment]
dupes #21 #45
