### ISSUE TITLE
Soundpacks webpage 404 error

### ISSUE THREAD

**Issue by fellelelle** [hainguyents13/mechvibes#163]
https://mechvibes.com/sound-packs/ seems to be down

**Comment by peuz1** [comment]
yeah it's down idk why tho

**Comment by 1Othman** [comment]
guys here it is https://docs.google.com/spreadsheets/d/1PimUN_Qn3CWqfn-93YdVW8OWy8nzpz3w3me41S8S494/edit#gid=0
