### ISSUE TITLE
Whenever I am playing CS:GO the sounds stop.

### ISSUE THREAD

**Issue by OsirisUser** [hainguyents13/mechvibes#168]
I don't know if this happens in other games but I am sure that whenever I ALT+TAB into CS:GO the sounds stop working. It would be nice if you could fix this minor bug!

**Comment by Riverql** [comment]
Yes this issue seems to happen on all games. Be sure to run the program as administrator. If you're using the enable at pc start up option, you will need to close and reopen it as administrator too. Hope this helps!
