### ISSUE TITLE
Mechvibes Stuck On Loading

### ISSUE THREAD

**Issue by AyoNikki** [hainguyents13/mechvibes#173]
I cant use Mechvibes because it says Loading... and it won't stop loading

**Comment by pr3Cash** [comment]
faced same problem but after installin the .deb pack i got no problem. it didn't got stuck. try it

**Comment by hawkiiie729** [comment]
how to install ,deb pack

**Comment by D-attebayo** [comment]
on Windows, just install Visual C++ then restart 
[Visual C++ Redistributable latest supported](https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170)

**Comment by D-attebayo** [comment]
on Windows, just install Visual C++ then restart
[Microsoft Visual C++ Redistributable latest supported downloads](https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170)

**Comment by arcadie1** [comment]
if you`re on windows , just reinstall the microsoft visual c++ , it worked for me tho

**Comment by NotLazy** [comment]
Possibly fixed #250
