### ISSUE TITLE
Website Isuues

### ISSUE THREAD

**Issue by SpicyChickenWing420** [hainguyents13/mechvibes#175]
Whenever I press 'More Sounds' on the Mechvibes program, it leads me to your website but all it says is Error 404 not found? Please fix this issue along with some more website issues. On a side note, I love this program very much, thank you!

**Comment by Zedroid** [comment]
in the custom channel from
https://discord.gg/ydZqwvrvYS
invite link in pin
https://www.youtube.com/watch?v=ekoKZ3wMHt8
