### ISSUE TITLE
High CPU usage on MacOS 10.13.6

### ISSUE THREAD

**Issue by nowakommunikation** [hainguyents13/mechvibes#177]
This is a nice program. I've installed it on a Linux machine and on a MacBook Pro running 10.13.6.

On the latter I noticed that the program (its Helper Renderer, according to the Activity Monitor, to be precise) uses a rather high percentage (25 %) of CPU power whenever you type. 

Is that normal? For continuous use this would be too much and heats up the MacBook more than it should for me. 

I haven't checked on the Linux machine so far.

**Comment by Farianit** [comment]
I also have the same issue on my MacBook with Apple M1.
I have a suggestion that it happens because the app doesn't have an Apple Silicon (arm) version, so it runs version for Intel via Rosetta 2.

**Comment by nowakommunikation** [comment]
(Sorry, opened a new issue instead of answering.)

I doubt it's got to do with Arm. My MacBook Pro is from 2010, macOS HighSierra.

**Comment by NotLazy** [comment]
Is this still an issue in latest version?

**Comment by nowakommunikation** [comment]
> Is this still an issue in latest version?

I'm happy to say that it doesn't. But it also won't produce any sounds. 

I tried your latest release on macOS 10.13.6. 

Then I went back to a release that I presumably used in 2022, let's say 2.0.0 and the keyboard was clicking again. 

Again, while typing, the program's files (main, renderer, etc.) use about 25 % CPU.
![Screen Shot 2023-12-25 at 13 05 53](https://github.com/hainguyents13/mechvibes/assets/44474606/1e81f1d0-88da-42b3-827d-8e92ce1992e5)

In the latest version 2.3.4 next to nothing. 
![Screen Shot 2023-12-25 at 13 09 29](https://github.com/hainguyents13/mechvibes/assets/44474606/20bec412-6283-4452-9960-946f36ca9edc)

Might this have anything to do with version 2.3.4 wanting access to the Accessibility pane in System & Privacy and version 2.0.0 not?

I did grant the access, and - after not sounds - removed the program and added it again. (Apparently this helps sometimes?) Still nothing.

**Comment by NotLazy** [comment]
Interesting. Are there specific sound packs that don't work or nothing works? I develop for mechvibes _on_ macOS and don't experience any issues with sound. Accessibility is definitely a requirement due to the capture of the keyboard across other apps, I'd recommend ensuring a full shutdown of the app after enabling accessibility access (use the quit option when you click the icon in the top bar, I forget what it's called at the moment)
