### ISSUE TITLE
It's stuck on loading and clicking more> open custom folder isn't working either.

### ISSUE THREAD

**Issue by mcdz** [hainguyents13/mechvibes#18]

**Comment by The-Danx** [comment]
For anyone else on MacOS you put the custom folder in the "Show Package Contents" of the application

**Comment by kris0725pl** [comment]
Hi all...i rename custom folder to Custom and run application as administrator. Works great ;)

**Comment by hainguyents13** [comment]
> For anyone else on MacOS you put the custom folder in the "Show Package Contents" of the application

Thank you man, thats really helpful!
