### ISSUE TITLE
R-Alt key keeps repeating the sound while held down

### ISSUE THREAD

**Issue by DonutWrecker** [hainguyents13/mechvibes#180]
Unlike other keys I've pressed so far, while the R-Alt key is held down, key sound keeps repeating. Other than that, occasionally, numpad keys repeat the key sound once more while they're held down.

Edit: Arrow keys have the same issue the numpad keys have.

**Comment by AspectOfJerry** [comment]
Duplicate of #161 
Yes it happens to me sometimes too.
