### ISSUE TITLE
Memory Leak, on MacOS 

### ISSUE THREAD

**Issue by henrychea** [hainguyents13/mechvibes#181]
Mechvibes takes more than 1gb of ram to run? Potential memory leak?

Device: 
MacOS Monterey 12.4, Apple M1

![image](https://user-images.githubusercontent.com/40254517/174444906-ab65e393-ca57-4962-af13-29fb7f828235.png)

**Comment by henrychea** [comment]
macOS Monterey 12.4, Apple M1

**Comment by AspectOfJerry** [comment]
Do you know for how long the app was running before it was taking 1GB?

**Comment by hitmacreed** [comment]
> Do you know for how long the app was running before it was taking 1GB?

Hi i have the same issue, i can say after 5 mn or less

**Comment by AspectOfJerry** [comment]
I'm not a macOS user but this is weird 🤔

**Comment by NotLazy** [comment]
There isn't a specific PR for this fix, but release v2.3.2 will include a fix which reduces memory usage by loading only the currently selected pack, as previous versions loaded all installed packs. I'm going to mark this as closed, for that reason, however if you find that in v2.3.2 you're still facing extreme memory issues, please feel free to open a new issue.

v2.3.2 is scheduled to be released before December 9th.
