### ISSUE TITLE
Can't join in Discord channel

### ISSUE THREAD

**Issue by ShadyTollipop** [hainguyents13/mechvibes#187]
Hi, Can't join in Discord channel.
Can u help me out?
Thanks!

**Comment by AspectOfJerry** [comment]
> Hi, Can't join in Discord channel.

If this is a Discord related issue and does not concern mechvibes, please contact Discord instead.

You can report bugs [here](https://support.discord.com/hc/en-us/articles/360046057772-Discord-Bugs), submit a request [here](https://support.discord.com/hc/en-us/requests/new), and email Discord at support@discordapp.com.

> Can u help me out?

If this is an issue related to mechvibes, please give us more information about your problem. Do you mean you can't join discord voice channels? I don't see how this is related to mechvibes though but there can be many causes to this. Maybe Discord is blocked so check with your network administrator.

**Comment by ShadyTollipop** [comment]
I think Mechvibes server banned me. Is there any way that admins can unban me?

**Comment by AspectOfJerry** [comment]
I can't help you with that sadly 😦.

**Comment by ShadyTollipop** [comment]
If you're in the server, can you please usernames of admins so i can contact them? thanks

**Comment by hainguyents13** [comment]
what is your discord usename? @ShadyTollipop

**Comment by ShadyTollipop** [comment]
Here: arcticboy#2316

Thanks a lot!

**Comment by ShadyTollipop** [comment]
@hainguyents13 
Bro i'm waiting for you for days.
Can you please help me out?
Thanks in advance!

**Comment by hainguyents13** [comment]
Just checked, you sent a spam message in #general so your ID was banned indefinitely from Mechvibes server, sorry for that

**Comment by ShadyTollipop** [comment]
Well let me explain then, my friend on Discord sent me a link and i clicked on the link then suddenly the link he/she sent was automatically sent to all of my joined servers. And almost all of them banned me, I can show you a proof if you want. All the servers about coding, programming like (python, c, c++, react, c#, java) BANNED me. I was so angry at the one who sent the link. So if you want to know more, you can ask questions. But please help me out !

Thanks!

**Comment by hainguyents13** [comment]
I can't find your ID from banned users, add me as your Discord friend so I can add you back manually hainguyen13#6233

**Comment by hainguyents13** [comment]
Just noticed one of the Mods unbanned you, so welcome back!

**Comment by ShadyTollipop** [comment]
Thanks tons man. I'm back. I hope it won't repeat again. Next time i'm gonna be careful with suspicious links!
Thanks again! <3
