### ISSUE TITLE
Minimize to Taskbar / Manual volume entry with typed digits or presets...

### ISSUE THREAD

**Issue by mikhasev** [hainguyents13/mechvibes#19]
Hi! 
First of all - amazing app! Cant find typewriter sounds for it though...
As for the issue - is it possible to minimize it to somehow to taskbar instead of system tray? I bet this wont cause sound delays... 
As for volume control, sometimes its handy to have the ability to type desired value instead of fiddling wit the slider, or even have 3 presets...
Thanks!

**Comment by hainguyents13** [comment]
thank you! 
I'm redesigning the UI and optimizing the code, so the next version will be released with 2 versions (minimal/full) the minimal will only include settings as you have seen on the current version and the full version will include more options to maximize app customization.
If you have subscribed to the newsletters on the homepage, I will send you a notification when the new version ready.

**Comment by mikhasev** [comment]
Great news! Cant wait!
