### ISSUE TITLE
not working with VSCode

### ISSUE THREAD

**Issue by lucianahanan** [hainguyents13/mechvibes#194]
Hi!

1. Is there a way to make windows startup call Mechvibes as administrator by default?

2. Also, the backspace doesn't make any sound with the Fire Emblem Soundpack. Any chance to add sound to it over there?

**Comment by syedahmad-1** [comment]
I am having the same issue. It is not working on vs code or any code editor. I'm Using Ubuntu's latest release. If you find any solution please let me know.

**Comment by syedahmad-1** [comment]
> Hi!
> 
> 1. Is there a way to make windows startup call Mechvibes as administrator by default?
> 2. Also, the backspace doesn't make any sound with the Fire Emblem Soundpack. Any chance to add sound to it over there?

Also, there is this extension named Keyboard sounds on vs code extensions and it does the same thing for VS Code Try it until this issue is solved.

**Comment by adi0sryan** [comment]
sorry what

**Comment by adi0sryan** [comment]
I litereally use this for my yt channel every day for vs code and it works like what

**Comment by relESCampONes** [comment]
On my machine it worked like this: going into the executable properties and selecting to run in administrator mode.
