### ISSUE TITLE
Is mechvibes a keylogger?

### ISSUE THREAD

**Issue by KostiaChorny** [hainguyents13/mechvibes#196]
Hi there,

It might be a stupid question (sorry), but how it actually works?
As I understand, app installs global system hook on keyboard events, so it can potentially log all keystrokes and send it anywhere.
Is there any guarantee that app is not capable to steal my passwords and credit card numbers?

Thank you a lot

**Comment by hainguyents13** [comment]
super thanks @Balls0fSteel 
@KostiaChorny You have my words, it's not a keylogger. The only thing that Mechvibes requests from the remote server is getting the version number from github for the update, nothing is being sent from your computer.
In the next version of Mechvibes, It will request more than the version number, such as new sound-packs from Mechvibes cdn...

**Comment by KostiaChorny** [comment]
@Balls0fSteel @hainguyents13 
Thank you for the answer! It's a great opportunity to improve skills in JS for me. 

As far as I know, in Electron app all source code is open and can be modified. Is it possible to sign the application, so it can't be changed after build. Without the signature, other malicious software or some nasty joker can change the code of installed app and send the keystrokes anywhere.

**Comment by ogbozoyan** [comment]
dude, just reverse code and check this out

**Comment by t3dium** [comment]
nah its safe, but in general its good practice to block internet access for fully offline apps like this, as even if it was it couldn't do anything. 

Simplewall's pretty convenient for this as it gives a yes/no prompt the first time a service/app tries to access the internet, and just adds a rule to windows firewall depending on the option chosen.

**Comment by KostiaChorny** [comment]
Thank you all,
just wanted to draw attention to security questions, which are usually ignored

**Comment by Shreyansh511** [comment]
searching issues for "safe" in 2026. thanky'all🙏🏻
