### ISSUE TITLE
Sound error

### ISSUE THREAD

**Issue by huynam27** [hainguyents13/mechvibes#2]
It is not really a bug, but in v2.0.0, fast typing will cause loss of speech, before this did not happen in version 1.4.x.
Cảm ơn vì đã tạo ra một sản phẩm tuyệt vời =]

**Comment by hainguyents13** [comment]
thanksssss
mà cụ thể lỗi như nào thế bro ơi :v

**Comment by takahatashun** [comment]
lỗi y như mình tả bên comment facebook lúc nãy nè

**Comment by hainguyents13** [comment]
Này không phải lỗi đâu mà do mình add cái thời gian giữa 2 phím là 30ms để tránh bọn unikey nó tự sửa phím ấy :( mà test lại không nghĩ đến trường hợp mình gõ còn nhanh hơn nên xảy ra vấn đề như trên, fix đã bỏ cái đó luôn rồi để tìm phương pháp khác xem sao, 2 bạn tải lại bản 2.0.1 trên trang chủ nha

**Comment by huynam27** [comment]
Okee!!
