### ISSUE TITLE
How to add run mechvibes on startup on Linux without gui? 

### ISSUE THREAD

**Issue by islamqasimov** [hainguyents13/mechvibes#208]
I just make it to open with crontabs but I don't want to always close this window of mechvibes

**Comment by blvck-major** [comment]
OK I got it just press _**enable on startup**_ on system bar (probably right top corner)
![image](https://user-images.githubusercontent.com/85077333/197360719-734d9c2f-4b38-417d-8cc5-7dfbfe1c7a87.png)
Looks like this (GNOME gui)

**Comment by Sharukki** [comment]
Does it work for you?

Because for me, after reboot the checkbox is unchecked everytime and mechvibes won't autostart
