### ISSUE TITLE
Mechvibes won't work on VMware Workstation

### ISSUE THREAD

**Issue by randev97** [hainguyents13/mechvibes#210]
When i open mechvibes and turn back to vmware it just stopping and not making any sound. When i quit vmware, mechvibes wents normal.

**Comment by AspectOfJerry** [comment]
Mechvibes doesn’t capture the key presses emitted in the virtual machine; hence, you don’t hear the sounds. However, since Mechvibes is installed on the host machine, when you leave the VM, you will hear the sounds.

**Comment by randev97** [comment]
> Mechvibes doesn’t capture the key presses emitted in the virtual machine; hence, you don’t hear the sounds. However, since Mechvibes is installed on the host machine, when you leave the VM, you will hear the sounds.

It still happens when not any virtual machine is running.

**Comment by AspectOfJerry** [comment]
😕

**Comment by Frannaaa** [comment]
Hello! You'll have to redownload Mechvibes on your VM! 

For linux, that's "sudo snap install mechvibes"

**Comment by adi0sryan** [comment]
Frannaaa, it is not that. He is not using a VM and is still having this issue. Please learn more information about the situation before coming to a conclusion.
