### ISSUE TITLE
Custom sound import not working.

### ISSUE THREAD

**Issue by cah192** [hainguyents13/mechvibes#211]
When i add custom sounds in the correct folder (by right clicking on the app in my system tray and clicking custom folder), after i restart the app, nothing works. The drop-down menu where all the sounds are doesn't click anymore and just shows up blank. The sound i have already selected doesn't work either in that no noise is coming from the app. 
OS: Windows 10
I also tried updating Microsoft Visual C++. It did not fix the issue.

**Comment by NotLazy** [comment]
The issue you're describing sounds like a known issue which is fixed in #250. The workaround is to ensure you don't have any folders in your mechvibes_custom folder, which doesn't contain a config.json

This means, no empty folders, and likely no zip files either.
