### ISSUE TITLE
Custom sound import doesnt work

### ISSUE THREAD

**Issue by JFjay1** [hainguyents13/mechvibes#213]
When I put in the folder for the sound from the official site into the custom sound folder when I restart mechvibes nothing loads in. The box where all the sounds should be is empty and nothing is visible. I've tried different sounds and even download Visual C++ but that didn't work either. The only way for it to work is by getting rid of folder I put into the custom sound folder. Please fix this issue
![image_2022-11-10_215206306](https://user-images.githubusercontent.com/117947426/201203340-b0363bc6-6774-4f2b-84cd-814f46cf1a19.png)

**Comment by api-was-taken** [comment]
Some files are just fucked lmao

**Comment by Fisterkoo** [comment]
This same happened to me. It is also very easy to solve issue. Just go to the code and get rid of the "," at the end of last line of code.
