### ISSUE TITLE
Can't find custom folder on linux xubuntu 

### ISSUE THREAD

**Issue by Frannaaa** [hainguyents13/mechvibes#215]
Hello friends! 
I downloaded mechvibes via the command "sudo snap install mechvibes" 

It runs but none of the keyboard profiles are there and I could not find the custom folder :< 
![screenshot](https://user-images.githubusercontent.com/96951334/202478358-c8549e7b-71a1-442c-8daa-912d3ff3f0e5.png)

checking my Mechvibes file in my home directory only shows 3 folders: "1" "common" "current"

**Comment by NotLazy** [comment]
Fixed #250
