### ISSUE TITLE
Doesnot work in vs code.

### ISSUE THREAD

**Issue by saroj-regmi** [hainguyents13/mechvibes#216]
I don't know but it works fine in all the places except for the places like vs code and other editors. I tried running it as the administrator but it also doesn't work.

**Comment by Gonchar76** [comment]
раньше у меня тоже не работало в vsc  но сегодня попробовал и звук радует строчу код и радуюсь спасибо тебе Друг!

**Comment by saroj-regmi** [comment]
Finally,
 I fixed it by running the **mechvibes as administrator** and then opening the vs code, 
Here opening the vs code means by opening it directly **( Not from the terminal )**. 
_Due to some reason it doesnot work in the terminal still, hope so it gets Fixed in near future._
