### ISSUE TITLE
Mechvibes keeps aborting when I try to install.

### ISSUE THREAD

**Issue by ThePersonhere** [hainguyents13/mechvibes#217]
basically yeah that's all I have to say, I download it in the default download spot fyi
![Capture](https://user-images.githubusercontent.com/119703933/205428682-9541a182-5dec-4897-9d2c-88368aaf561a.PNG)

**Comment by stysan** [comment]
make sure your disk space is enough, mechvibes takes roughly around 300 mb in size (as i can remember)

**Comment by Kani09** [comment]
I am also suffering from same problem
and i have 200gb extra in my disk

**Comment by RodriVinciV2** [comment]
i figured out, i uninstall it in a bad way and when i tryied to install it again, gives me the error from the pic. I just uninstall it from control panel and i install it again. It works for me

**Comment by NotLazy** [comment]
This appears to be an issue with electron-builder, which we cannot fix. The work-around is to use the uninstaller, which we've made permanently available at https://mechvibes.com/windows/Uninstall_Mechvibes.exe
