### ISSUE TITLE
Remove the random soundpacks from Mechvibes Linux AppImage

### ISSUE THREAD

**Issue by writeblankspace** [hainguyents13/mechvibes#219]
Used to use it on Windows and loved it, now using Ubuntu. I downloaded the AppImage and I like it but it bothers me that there are random soundpacks - which sometimes go on by accident and take forever to finish their sounds - and one of them isn't even sfw. Would be nice if they're opt-in and not included automatically. The Windows release is fine and doesn't have any weird extras - just keyboard sounds like Cherry MX and stuff. Thanks.

![image](https://user-images.githubusercontent.com/75297066/206899270-1d0d74b6-795c-4217-a7ea-ae577d481b7e.png)

**Comment by NotLazy** [comment]
Please let me know if this is fixed in the latest version or not.
