### ISSUE TITLE
It sounds weird.

### ISSUE THREAD

**Issue by andriemc** [hainguyents13/mechvibes#223]
Like it sounds like it's lagging but isn't. Please fix IT NOW.

**Comment by adi0sryan** [comment]
Its your computer, bozo.

**Comment by ANDREI12333** [comment]
@adi0sryan it was fine before kid.

**Comment by AspectOfJerry** [comment]
> sounds like it's lagging

What do you mean by that?

Are you talking about a delay? If so, it might be related to #222, #12, #13, #142, and #151
