### ISSUE TITLE
No easy to find manual on how to install a soundpack

### ISSUE THREAD

**Issue by Azarien** [hainguyents13/mechvibes#225]
There's "More sounds..." link in the app but I couldn't find any description on how to actually install a soundpack once it is downloaded: not in the app itself, not on the website on "Custom sound-packs" page, and not on the spreadsheet with all the links.

**Comment by NotLazy** [comment]
We're soon going to be launching a new website which will allow you to install packs directly from the website, without having to manually extract, as well as test keyboard sounds directly on the site before installing them.

**Comment by keenahn** [comment]
@Azarien download the soundpack and extract it to `$HOME/mechvibes_custom`, restart mechvibes and you'll see it under custom packs. Yeah it sucks having a hardcoded directory in your home, but that's why v3 will be better :)
