### ISSUE TITLE
New features request

### ISSUE THREAD

**Issue by Seamas73** [hainguyents13/mechvibes#227]
Please add in future releases:
1. Option to set up a hotkey for muting/unmuting program sound;
2. Parameter that allows the program to start minimized to the system tray at the OS start.

**Comment by patolas01** [comment]
- Check if the key is still down or if it has already been released to split the click sound and the key recoil sound.
(it would be necessary to update all the sound packs I think)

**Comment by AspectOfJerry** [comment]
> split the click sound and the key recoil sound

#146, #49, #21

**Comment by Jacksonmills** [comment]
Sound offset, for me I would like it to offset a bit as I hear a delay from my RL keystrokes to the mechvibes sound
