### ISSUE TITLE
There is a delay in the sound after mech vibes is left idle on windows

### ISSUE THREAD

**Issue by omk12** [hainguyents13/mechvibes#229]
When u dont type for a while. the program goes to sleep ig. when u type again the sound comes after  1-2 seconds. this keeps happening.  Can someone help me with this?

**Comment by Jacksonmills** [comment]
I just noticed a similar issue, seems restarting the app made it better again... I was kinda thinking along with this having some kind of delay or adjustment to the timing of when it triggers would be nice as its a little late for me even when working correctly.

But I definitely noticed this bug as well

**Comment by vivekkpatel** [comment]
I am recording programming tutorial with keyboard sounds and there's 1-2 second delay for my keyboard stocks

**Comment by Angel-Ponce** [comment]
Same problem

**Comment by NotLazy** [comment]
Dupe of #12 and #13
