### ISSUE TITLE
Mechvibes asking for Google Login after downloading pack 

### ISSUE THREAD

**Issue by kristoferdowe** [hainguyents13/mechvibes#23]
Mechvibes is asking for personal login information to Google after downloading a demo pack. Closing via task manager, deleting and reinstalling does not fix the issue. 
![mechvibessupport](https://user-images.githubusercontent.com/57381168/93515872-436c4100-f8f7-11ea-8856-03d50d9d98f2.PNG)

**Comment by hainguyents13** [comment]
which button did you clicked leading to this?

**Comment by kristoferdowe** [comment]
> which button did you clicked leading to this?

This happened after following instructions to download new sound packs. I downloaded one soundpack in particular (i think it's called sine wave beeps) and then this issue started.

**Comment by hainguyents13** [comment]
can you record a video to demo this issue? because I can't figure out how Mechvibes redirected to this screen

**Comment by kristoferdowe** [comment]
unfortunately, I cannot open the app to the normal UI screen. It defaults to this screen every time, even if I delete the files for the app. 

I think the default action for loading packs is targeting the pack that I downloaded by targeting Google Drive, where the pack is saved. I could be wrong, but maybe something to do with event.preventDefault

**Comment by hainguyents13** [comment]
this app does not point to any resource from anywhere but the app installed folder so this behavior is so weird. 
I will upload a new version within this week, so in the meantime can you try to uninstall it completely by using Total Uninstaller?

**Comment by kristoferdowe** [comment]
I understand this app doesnt point to outside resources once sounds are loaded, however in this line, it looks like it is pointing to the element body:

 sound_data[kc].once('load', function () {
            all_sound_files[`${pack_data.pack_id}-${kc}`] = true;
            checkIfAllSoundLoaded(status_display_elem, app_body);

**Comment by hainguyents13** [comment]
it points to the document body to remove the loading class from the body https://github.com/hainguyents13/mechvibes/blob/35ed8e8032606765b61fb4270a7a9a85ae356e0c/src/app.js#L107

**Comment by kristoferdowe** [comment]
I was able to fix by reinstalling after totally removing software. Thanks for helping!

**Comment by hainguyents13** [comment]
> I was able to fix by reinstalling after totally removing software. Thanks for helping!

you are welcome!
