### ISSUE TITLE
Mechvibes not working in the game

### ISSUE THREAD

**Issue by GGSHHS** [hainguyents13/mechvibes#231]
Help me with mechvibes, its not working in the games, but working on discord and google chrome and another programs.

**Comment by yohanselias5-hue** [comment]
me too

**Comment by yohanselias5-hue** [comment]
wtf 2023

**Comment by GGSHHS** [comment]
> wtf 2023

Hahaha brooo, i was so shocked when i received fricking reply from mechvibes 2023 issue lmaooo

**Comment by GGSHHS** [comment]
Forced me to sign back in on git hub man
