### ISSUE TITLE
#_Sound issue when pressing two keys at the same time for a while

### ISSUE THREAD

**Issue by manuelhonoredesousa** [hainguyents13/mechvibes#233]
In normal use, when you tap on two keys without stopping, it makes a lot of noise as if you are clicking the same key several times.

Taking into account that the software seeks to bring a more real experience to the user, it would be good to review this because in real life when we paste on two or more tiles at the same time (mechanical keyboard), it doesn't make the sound as if we were pressing it several times

**Comment by NotLazy** [comment]
cannot repro
