### ISSUE TITLE
MECHVIBES NOT WORKING

### ISSUE THREAD

**Issue by blackgoddemon** [hainguyents13/mechvibes#237]
Hey,i was using mechvibes tomorrow its working fine but today it suddenly stops like no sound  is coming. i reinstall and also run it as administrator but no sound is coming pls help its just stay in tray and nothing happnens pls help me :(

**Comment by imasupercoolguy** [comment]
same thing been happening to me

**Comment by keshavv17** [comment]
I installed mechvibes yesterday and application is not showing any sound pack only loading indefinitely.

**Comment by blackgoddemon** [comment]
> same thing been happening to me

Did you find the reason or solution

**Comment by keshavv17** [comment]
> 

Nope, it was working fine for me but i changed my device and when i reinstalled this error occurs.

**Comment by sdGGDSBSDVB** [comment]
yea. same. it doesnt show ANY sounds at all.

**Comment by keshavv17** [comment]
download visual c++ redistributable and it'll work fine. For me it's working fine now.

**Comment by sdGGDSBSDVB** [comment]
did that also but no fix..

**Comment by sdGGDSBSDVB** [comment]
> what version of visual c++?

**Comment by anirudh12032008** [comment]
same issue

**Comment by HariAcharya80** [comment]
For guyz wondering what is the fix, you need to be more specific on issues you are having and your environment. 

> download visual c++ redistributable and it'll work fine. For me it's working fine now.

This will fix the problem for must windows versions including windows 7, 8 and 10 @ **https://github.com/electron/electron/issues/10291**

For Xfce, It is working completely fine but for GNOME or other desktop managers based on GNOME, it needs a fix @ **https://github.com/hainguyents13/mechvibes/issues/238**

>I installed mechvibes yesterday and application is not showing any sound pack only loading indefinitely.

@keshavv17 What is the system you are running and it's version? also which version of mechvibes?

**Comment by GodswillOmondi** [comment]
I've just installed the file in Ubuntu and no sound I don't understand why
