### ISSUE TITLE
Understanding The config.json file

### ISSUE THREAD

**Issue by AvikArefin** [hainguyents13/mechvibes#241]
What does 'defines' field represent?
I assumed the keys are for the specific keys and the array is for time and duration in the audio file. But which key represents which number? If you cared to explain...

**Comment by hainguyents13** [comment]
it used for the Editor, not the users. I'm working on a new version for better customize experience

**Comment by AvikArefin** [comment]
thanks for the quick reply!
But I still wanted to know how you mapped the keys with the numbers. I tried to match it with keycodes, but I was unable to as the mapping seemed different.
for example in your case:
'Tab' is defined for number 15 (if I am not wrong)
but the keycode for that is 9.

I could have misunderstood some of the things, but how are they mapped?

**Comment by hainguyents13** [comment]
You can find the definitions here [src/libs/keycodes.js](https://github.com/hainguyents13/mechvibes/blob/master/src/libs/keycodes.js)
