### ISSUE TITLE
mechvibes 2.3.1 showing blank

### ISSUE THREAD

**Issue by okpeters2k21** [hainguyents13/mechvibes#242]
mechvibes was working fine on my computer until i opened the editor to create a new soundpack. after re-opening the program, it shows no volume and no options for keyboard sounds. i have visual c++, but that did not help. please help ;-;

**Comment by NotLazy** [comment]
Your issue loosely sounds related to #250, however, I'd recommend visiting our discord for more help, if you haven't already.

**Comment by andika207** [comment]
WoW.... I thought this repo was dead. are you the new developer ? @NotLazy

**Comment by NotLazy** [comment]
@andika207 hainguyents13 is still the main developer but I've been given permission to manage the GitHub, help out in the discord, and I'm working on essentially a brand new website under the hood, as I'm rewriting the backend from scratch, and adding a handful of new features to the frontend.

**Comment by andika207** [comment]
> I'm rewriting the backend from scratch, and adding a handful of new features to the frontend.

if you are working on this same project I don't quite understand why did you fork it and create your own repo ?

my main interest is the support for NT 5.1 I hope you find a way to sort this out https://github.com/hainguyents13/mechvibes/issues/4

**Comment by andika207** [comment]
> I'm working on essentially a brand new website under the hood

the other website looks fine to me.

I just need some basic instructions for dummies because I have no clue how to add more sounds to mechvibes

**Comment by NotLazy** [comment]
> if you are working on this same project I don't quite understand why did you fork it and create your own repo ?

By using my own repo to test changes before applying them here, I can keep the history cleaner and make experimental changes that don't make it to release.

**Comment by NotLazy** [comment]
> the other website looks fine to me

I'm adding the ability to view, test and install sound packs directly from the website, among other things. But that's the biggest upgrade I'm working on. So people won't need a guide for dummies because it'll be 1 button on the website and 1 button in the app to install new packs.

The button in the app is to confirm the installation.

**Comment by andika207** [comment]
>because this app based on Nodejs an Electron and a machine that runs XP might not be able to handle it

WoW ! I thought you had thrown the towel in. https://github.com/hainguyents13/mechvibes/issues/4#issuecomment-1650358107

I didn't expect to see you here anymore because @NotLazy seems to be the only active dev left

**Comment by hainguyents13** [comment]
> 
> I didn't expect to see you here anymore because @NotLazy seems to be the only active dev left
he is, for now, since my right shoulder hasn't fully recovered, now Im replying using my left hand on my cellphone haha

**Comment by andika207** [comment]
> Why do you want support for an operating system that's end of life and out of support? 
I don't plan on adding support for outdated operating systems which don't even get security updates anymore.

this is kind of asking... why do you get married with the same wife forever ?

why is it mandatory to use the W10/W11 shit if we don't like it ?

there are tons of software utilities that have not been updated for ages and they work perfect with any Windowz so why bother and come up with the security updates excuse ? 

do you also exclude Win7 which si outdated for you ? LOL
**mechvibes** works on Win7 and it won't stop from working because of the lack of security patches

**Comment by andika207** [comment]
> he is, for now, since my right shoulder hasn't fully recovered, now Im replying using my left hand on my cellphone haha

OK. hope you recover well and learn how to back port it to NT 5.1  https://github.com/hainguyents13/mechvibes/issues/4#issuecomment-1650358107
the other one has lately been closing a bunch of issues topics so I'm not sure everything got fixed.

**Comment by NotLazy** [comment]
> do you also exclude Win7 which si outdated for you ? LOL

Yes I do, I make little attempt to provide backwards compatibility for unsupported operating systems or browsers. 

If @hainguyents13 wants to attempt it I won't fight it by any means, but I personally won't be attempting to support it.

**Comment by andika207** [comment]
>  I make little attempt to provide backwards compatibility for unsupported operating systems or browsers.

that's a stupid excuse because M$ updates won't fix mechvibes related issues

fortunately there are persons who don't think this way.

it's up to you to decide whether you want to have more or fewer users.

**Comment by hainguyents13** [comment]
@andika207 tbh, I truely want to make mechvibes work for everyone, but there are limits that I have to admits since this app depends on thirdparty libraries such as Nodejs, Electron, iohook and they dropped windows XP support already
