### ISSUE TITLE
2.3.0 Setup Not Working

### ISSUE THREAD

**Issue by pupeeb** [hainguyents13/mechvibes#245]
Mac user here, when i open the set up it gives me the error "the application cant be opened -10661"

**Comment by NotLazy** [comment]
Error 10661 is a “kLSExecutableIncorrectFormat” error. Indicating the apps you're downloading aren't executable or have an incorrect format. The error also appears if you don't have the correct permissions to run apps.

I suggest checking if you have downloaded the right release, (as a mac user you should be using the .dmg) and ensuring you have permission to authorize the launch of unverified apps, as this app and it's developer have not been verified by apple.
