### ISSUE TITLE
Installer freezing and not installing files

### ISSUE THREAD

**Issue by Robbonabbo** [hainguyents13/mechvibes#258]
Hi I've used mechvibes in the past and uninstalled along time ago. I recently needed to install it again but the installer would open and the bad would freeze mid install. It wont say "Operation Aborted" but it will just say "Installing..." like it normally would. I've tried different methods:

>Clearing up old files from previous installs
>Fresh installing after re-start
>Running as administrator
>Disable my antivirus
>Looking for other conflicting software

Free disk space: 120 Gigabytes
Windows 10 22H2, 64 Bit, Build 19045.3570

Could anybody help? Thank you in advance

**Comment by Robbonabbo** [comment]
Fixed: Check for corrupted or hidden files with the name "Mechakeys"

**Comment by hainguyents13** [comment]
> Fixed: Check for corrupted or hidden files with the name "Mechakeys"

thank you @Robbonabbo
