### ISSUE TITLE
Shortly laggy sounds after not using the keyboard for a bit

### ISSUE THREAD

**Issue by ghoomfrog** [hainguyents13/mechvibes#277]
When I don't use the keyboard for a bit, the next few keys I hit get delayed sounds. I'm using Windows 10 btw.

**Comment by NotLazy** [comment]
https://github.com/hainguyents13/mechvibes/issues/12
https://github.com/hainguyents13/mechvibes/issues/13
https://github.com/hainguyents13/mechvibes/issues/142
https://github.com/hainguyents13/mechvibes/issues/151
