### ISSUE TITLE
iohook issues when installing deps

### ISSUE THREAD

**Issue by mattveraldi** [hainguyents13/mechvibes#284]
Hi,
I am trying to install dependencies with `npm install` but iohook always fails to build.
Which version of node did you use to build the project?

thanks

**Comment by NotLazy** [comment]
I'm using node v18 with no issues, what version of node are you experiencing this issue?

**Comment by mattveraldi** [comment]
I was able to successfully install it with the current Node LTS on a fresh Debian 12 installation.

The issue reproduces on Windows, if you install NodeJS both on the host and the `wsl` using `nvm-windows` and `nvm`. My issue was not related to an issue with this repository so I am going to mark it as closed.

Thank you very much.
