### ISSUE TITLE
Active volume adjustment

### ISSUE THREAD

**Issue by bAN0NYM0US** [hainguyents13/mechvibes#289]
This is a feature request to add active volume adjustment so the keyboard sounds don't exceed a specific volume as system volume is adjusted.

For instance, if the app volume is set to 50%, and computer volume is set to 50%. It runs reversed off of each other. So if the computer volume goes up to 75%, the app volume actively lowers to 25% making sure the keyboard sounds are always the same volume regardless of the system volume. The same would apply in a reverse instance where system volume goes down to 25%, the app volume goes up to 75%.

This would just add a very natural liner sound to the keyboard that is less artificial as the clicks get super loud when watching a twitch stream or something where you want your volume higher but are still actively typing in the chat without having to open the app controls every time to manually adjust the click volume secondary to your system volume every time it's adjusted.

**Comment by hainguyents13** [comment]
Pratical and brilliant idea! surely work on it

**Comment by NotLazy** [comment]
@bAN0NYM0US @hainguyents13 Added in #293 though, I have to mention it's not as impressive as I expected due to technical limitations.

**Comment by hainguyents13** [comment]
@NotLazy  okay so just skip this for now

**Comment by NotLazy** [comment]
> @NotLazy  okay so just skip this for now

It's been added 🤔

**Comment by hainguyents13** [comment]
> It's been added 🤔

Sorry misunderstood, I though you skip it

**Comment by BrajBliss** [comment]
Can you explain this again @NotLazy I tried this feature but I don't notice any difference. Thanks.
