### ISSUE TITLE
THIS PROGRAM IS A VIRUS I CHECKED THE SOURCE CODE

### ISSUE THREAD

**Issue by 081isaac** [hainguyents13/mechvibes#290]
self-explanatory

**Comment by hainguyents13** [comment]
please add more details

**Comment by NotLazy** [comment]
You can't make an issue like this and not reference the lines of code that make this a virus and why.

**Comment by thalessalazar** [comment]
I analyzed all the source code for anything malicious, but found nothing. The implementation is simple and the dependencies are reliable.
