### ISSUE TITLE
Editor for creating custom Key noise packs 501 error

### ISSUE THREAD

**Issue by Lukas-Batema** [hainguyents13/mechvibes#296]
![image](https://github.com/hainguyents13/mechvibes/assets/55695493/17a88e2e-2c36-4846-bec5-3e9d4cf17648)

https://mechvibes.com/editor/

Seen here https://github.com/hainguyents13/mechvibes/wiki/Soundpacks#before-you-start-creating-a-new-soundpack

**Comment by NotLazy** [comment]
https://github.com/hainguyents13/mechvibes/wiki

**Comment by Lukas-Batema** [comment]
> https://github.com/hainguyents13/mechvibes/wiki
> 
> > This wiki is incomplete and may contain information which is not accurate. Please be sure to check-in with us on discord to verify any information contained within this wiki.
> 
> Plus, as the page says, it's not implemented, but is being worked on, meaning it _is_ coming, but it's not available yet 

I don't see how adding something that hasn't been implemented yet is "incomplete" to add to the wiki. It makes it not accurate in a way that doesn't pertain to the wiki, hence why I opened this issue. I’m sure any reasonable person would do the same with similar logic behind it.

**Comment by NotLazy** [comment]
> I don't see how adding something that hasn't been implemented yet is "incomplete" to add to the wiki. It makes it not accurate in a way that doesn't pertain to the wiki, hence why I opened this issue. I’m sure any reasonable person would do the same with similar logic behind it. This shows a lack of effort to make things professional-looking. I’m going to find another programme for this, as it seems that this will not be fixed. 

Ok, I'll take down the wiki tomorrow.

**Comment by NotLazy** [comment]
> This shows a lack of effort to make things professional-looking. I’m going to find another programme for this, as it seems that this will not be fixed.

The wiki is in-progress, which is precisely *why* I put that warning on the front page. I'm working on 3 things for this app at once, and I'm only one person. The main purpose of putting that documentation out early was to provide people who are seeking and suggesting new config versions, that, *yes*, it is planned, it is coming and we don't need further suggestions about features "to-be" in upcoming config versions. The wiki is **new**. Mechvibes hasn't used it in the past. The place for questions and information has always been in mechvibes' discord, which you can find a link to [on our website](https://mechvibes.com). This includes a FAQ which tells you how to create your own soundpacks.

As for finding another program over this, you're definitely free to do so, though personally I feel it's excessive over an in-progress wiki. But to that end, mechvibes is the **only** completely free application which does what mechvibes does. Alternatives require you to create an account and either pay or accumulate points.
