### ISSUE TITLE
AppImage for v2

### ISSUE THREAD

**Issue by probonopd** [hainguyents13/mechvibes#3]
Hi, will there be an AppImage? Thanks.

**Comment by hainguyents13** [comment]
I'm building an AppImage version now!

**Comment by hainguyents13** [comment]
> Hi, will there be an AppImage? Thanks.

I have uploaded the AppImage version, you can check it in releases. Thank you!

**Comment by hainguyents13** [comment]
@probonopd Thanks for adding Mechvibes to AppImageHub! You are the best sir!
