### ISSUE TITLE
custom folder gets deleted when application is closed

### ISSUE THREAD

**Issue by Chowtown** [hainguyents13/mechvibes#30]
I suspect that when I close the program the temp file gets deleted. I've made sure that my system does not delete files that aren't being used.

**Comment by hainguyents13** [comment]
pretty sure you are using the portable version, the full version may not face this issue

**Comment by Chowtown** [comment]
Where is the full version?

**Comment by hainguyents13** [comment]
on the home page, setup file

**Comment by Chowtown** [comment]
I installed the full version, but mechvibes just appears empty. Do I have to wait that out? Thank you so much for the help

**Comment by Chowtown** [comment]
I was able to get it to load, but if I add a custom folder, the application won't load

**Comment by Chowtown** [comment]
I still can't figure out the issue, do you have an idea?

**Comment by TahirMurata** [comment]
In the new version, the custom folder is in the root folder of the user so to access it go to the mini task on the right downside (The arrow pointing up) and right-click it, and click on the Custom Folder.
