### ISSUE TITLE
Wayland Support

### ISSUE THREAD

**Issue by Redoxahmii** [hainguyents13/mechvibes#300]
Any application that is running on wayland this application has no sound.
I am an Arch and Gnome and most of the things that i use for typing are now running on Wayland and not having this work is very annoying.

**Comment by NotLazy** [comment]
Dupe of #86

**Comment by Redoxahmii** [comment]
Welp hopefully the bug is fixed as this is now forcing me to run apps with x11 even for supported wayland applications just to have the sound.
