### ISSUE TITLE
How to make it open on startup in the background without the menu showing,

### ISSUE THREAD

**Issue by HatemElZomor** [hainguyents13/mechvibes#304]
I want it only in tray on startup without it opening up the menu every time I reboot my pc.
Any suggestions?

Thank you!

![image](https://github.com/hainguyents13/mechvibes/assets/54311172/90a14c4d-cf05-4be1-80b8-193807886de1)

**Comment by NotLazy** [comment]
v2.3.5 supports this and will be released soon.
