### ISSUE TITLE
Startup Issue with Mech Vibes on Windows

### ISSUE THREAD

**Issue by Maadlou** [hainguyents13/mechvibes#309]
I've been encountering an issue with Mech Vibes on Windows following the latest update. When my PC starts up and Mech Vibes launches with Windows, the app does not function properly initially. I have to close Mech Vibes and then relaunch it manually for it to work correctly. This problem started occurring after the recent update. It would be greatly appreciated if this issue could be addressed to ensure a smoother startup experience with Mech Vibes on Windows systems.

**Comment by febalci** [comment]
Same for me on Windows 11, Mechvibes 0.3.0
