### ISSUE TITLE
Crashing on Linuxmint 21 with Cinnamon

### ISSUE THREAD

**Issue by davidchua** [hainguyents13/mechvibes#314]
On Linuxmint 21 with Cinnamon, after installing with the latest `.deb` file, running mechvibes crashes with the following error:

```
11:14:46.215 › App is ready and has been initialized
11:14:53.246 › Loading 11
11:14:53.509 › loaded
[8466:0511/111456.477704:FATAL:gpu_data_manager_impl_private.cc(894)] The display compositor is frequently crashing. Goodbye.
Trace/breakpoint trap (core dumped)
```

```
x@soundwave:~/codebase/facebook-backend$ dpkg -s mechvibes
Package: mechvibes
Status: install ok installed
Priority: extra
Section: default
Installed-Size: 185652
Maintainer: Hai Nguyen <hainguyen.ts13@gmail.com>
Architecture: amd64
Version: 2.3.4
Depends: libgtk-3-0, libnotify4, libnss3, libxss1, libxtst6, xdg-utils, libatspi2.0-0, libuuid1, libappindicator3-1, libsecret-1-0
Description: 
  Play mechanical keyboard sounds as you type.
License: MIT
Vendor: Hai Nguyen <hainguyen.ts13@gmail.com>
Homepage: https://mechvibes.com
```

**Comment by NotLazy** [comment]
Are you running headless? Mechvibes doesn’t support that. Have you
installed the dependencies listed in the log you provided? Mechvibes on
Linux has pre-requisites that I’m not confident get automatically installed.

**Comment by joezhouchenye** [comment]
Ubuntu 23.10 has the same problem.

It seems a problem with libappindicator3-1 in Depends. Ubuntu 23.10 uses libayatana-appindicator3-1 by default.

**Comment by joezhouchenye** [comment]
https://github.com/RocketChat/Rocket.Chat.Electron/issues/1975#issuecomment-1016820780

According to this comment related to libappindicator3-1, Debian based system has switched to libayatana-appindicator for over 2 years.

**Comment by Omaeda** [comment]
I think it's the same error as in #171

**Comment by NotLazy** [comment]
> [RocketChat/Rocket.Chat.Electron#1975 (comment)](https://github.com/RocketChat/Rocket.Chat.Electron/issues/1975#issuecomment-1016820780)
> 
> According to this comment related to libappindicator3-1, Debian based system has switched to libayatana-appindicator for over 2 years.

Unfortunately, we have no control over electron's dependencies, and face issues with upgrading past electron 12 at this time due to upstream dependencies.
