### ISSUE TITLE
doesn't work on sonoma 14.4.1 macbook pro 16 m1

### ISSUE THREAD

**Issue by AHTOOOXA** [hainguyents13/mechvibes#315]
no sound is being played dunno why

**Comment by emil-rugby** [comment]
Affirmative! And please make for AMD64 processors (M1-M3)

**Comment by NotLazy** [comment]
Ensure if you're upgrading from v2.3.1 or below that you reset mechvibes accessibility settings, due to differing app publishers.

Also, at this time, we're unable to provide an arm64 build for m series macbooks due to the technology used in mechvibes.
