### ISSUE TITLE
Uninstall default packs

### ISSUE THREAD

**Issue by Giatroo** [hainguyents13/mechvibes#316]
I'm using mechvibes for about two weeks, and I'm really enjoying it. 

Is there a way to remove default soundpacks? I would like to use `Set random sound` more, but it often goes to a default pack that I don't like quite well, but I can't uninstall them to leave only the ones I like. 

Also, it would be very nice to have some setting that changes the soundpack everytime I log into my machine =D

Thank you very much!

**Comment by NotLazy** [comment]
Apologies for the bot. I've been having issues with it.

Onto your question, depending on your platform, you may or may not be able to remove them already.

Search your file system for the file names located in this repo, under src/audio if you find them just delete them.
