### ISSUE TITLE
Crash on system startup when system launch on system startup setting is disabled

### ISSUE THREAD

**Issue by FreePhoenix888** [hainguyents13/mechvibes#319]
I have installed mechvibes and it was working only with specific option: `mechvibes --in-process-gpu` (this is noted in another issue). I have not checked "Enable on startup" option but for some reason when I rebooted my pc I saw window like this
![image](https://github.com/hainguyents13/mechvibes/assets/66206278/ca367df0-2d44-4cbf-b587-0fea7f27be12)
I have checked /var/crash folder for more information and there was only mechvibes, no other application
Here is crash info (there are 2 crash files):
[_opt_Mechvibes_mechvibes..zip](https://github.com/user-attachments/files/15798839/_opt_Mechvibes_mechvibes.zip)

**Comment by NotLazy** [comment]
I would suggest checking your systems startup programs and potentially re-installing mechvibes. The only reason I can assume mechvibes would be attempting to launch at startup is if you had turned it on at some point in the past, and then turned it off and for some reason, it failed to disable.
