### ISSUE TITLE
custom sounds folder not appearing

### ISSUE THREAD

**Issue by sqwerlman** [hainguyents13/mechvibes#32]
I tried to install a custom sound pack, but I was not able to find anything. I tried making a custom folder, but nothing happened. Is there a newer download I need to find?

**Comment by hainguyents13** [comment]
which OS are you using?

**Comment by sqwerlman** [comment]
I am using windows 10

**Comment by sqwerlman** [comment]
after a reinstall it still looks like this: 
![Uploading image.png…]()

**Comment by hainguyents13** [comment]
I cant see the image

**Comment by sqwerlman** [comment]
It's basically the same as the tutorial on the website, but it's missing the first folder, custom.

**Comment by hainguyents13** [comment]
you have to create it, then copy the custom pack folder into it and restart mechvibes

**Comment by sqwerlman** [comment]
alrighty thanks!

**Comment by TahirMurata** [comment]
In the new version, the custom folder is in the root folder of the user so to access it go to the mini task on the right downside (The arrow pointing up) and right-click it, and click on the Custom Folder.

**Comment by commandergoose** [comment]
dear friends. i made an account just to let you all know that i've found a solution
yall probably arent moving the right folders into the custom folder.

basically, once you extract
 something, you'll want to double click on the folder and see if theres a second folder in the first one. 
 
![image](https://user-images.githubusercontent.com/81006539/111861832-7a56fa00-890e-11eb-9d1f-6ade02065fcd.png)

![image](https://user-images.githubusercontent.com/81006539/111861844-89d64300-890e-11eb-839b-d0f5b9e19fec.png)

you'll want to drag that second one into the custom sounds folder thingy. worked for me, it might work for you! :]

also. if you open the folder and it takes you right to the sound file thingies, then it's fine and you can drag it right into the custom folder. hope this helps some of u :0

**Comment by lojithv** [comment]
Check system tray icons :)

![Screenshot_87](https://github.com/hainguyents13/mechvibes/assets/74459314/b64489fe-c6e5-4ffd-9bd2-523aa978584f)

**Comment by Kostas865** [comment]
> I tried to install a custom sound pack, but I was not able to find anything. I tried making a custom folder, but nothing happened. Is there a newer download I need to find?

I cannot do it. I am trying many days now .
I choosed a typewriter sound, it sent to download files. Then i extract file to custom folder. I open the app but the custom sound doesn't appear...

**Comment by Kostas865** [comment]
> you have to create it, then copy the custom pack folder into it and restart mechvibes

**Comment by Kostas865** [comment]
I cannot do it. I am trying many days now .
I choosed a typewriter sound, it sent to download files. Then i extract file to custom folder. I open the app but the custom sound doesn't appear...
Can you help.me step by step?

**Comment by Kostas865** [comment]
> alrighty thanks!

Did you find a solution? I cannot do it. I am trying many days now .
I choosed a typewriter sound, it sent to download files. Then i extract file to custom folder. I open the app but the custom sound doesn't appear... Can you help me step by step please?

**Comment by NotLazy** [comment]
@Kostas865 Ensure the folder in your custom directory contains config.json at the root level. Sometimes when we unzip files, they'll put the files in a sub directory. [See here](https://github.com/hainguyents13/mechvibes/wiki/Soundpacks) for examples on valid folder structure.
