### ISSUE TITLE
Move logfile and custom config to standard locations

### ISSUE THREAD

**Issue by alirezaalavi87** [hainguyents13/mechvibes#325]
Hi. having mechivbes_custom directory and a logfile in your base home directory really doesn't make sense. 
It would be much better if we moved to standard XDG paths.
`~/.config/mechvibes` for custom config and soundpacks, and `/var/log/mechvibes` or `~/.cache/mechvibes` for logs.

**Comment by NotLazy** [comment]
Planned for next release, just working out some kinks with migration.

**Comment by NotLazy** [comment]
Added with [492e65e](https://github.com/hainguyents13/mechvibes/commit/492e65e211db18d4cb217120dd0a9cf9ba2eb5f3)
