### ISSUE TITLE
Absolute volume

### ISSUE THREAD

**Issue by intzaaa** [hainguyents13/mechvibes#326]
The sound volume of the keyboard should not change with the change in the volume of the system.

```js
let volume = () => inAppVolume / systemVolume 
```

**Comment by NotLazy** [comment]
This has already been added as an optional feature and will be included in the next update.

**Comment by intzaaa** [comment]
> This has already been added as an optional feature and will be included in the next update.

When will the next version be released? Thanks.

**Comment by intzaaa** [comment]
> This has already been added as an optional feature and will be included in the next update.

When will the next version be released? Thanks.
