### ISSUE TITLE
After uninstall /deleting

### ISSUE THREAD

**Issue by grpnpraveen** [hainguyents13/mechvibes#33]
These sounds are still working.
How to stop  it completly

**Comment by hainguyents13** [comment]
right click the icon in system tray and select "Exit"

**Comment by googlovescars** [comment]
mine still makes the little clicky sound when you turn it to 0 volume.

**Comment by googlovescars** [comment]
after i deleted

**Comment by grpnpraveen** [comment]
Even for me @googlovescars  and sometimes these sounds turns off for a while after Mechvibes started.
