### ISSUE TITLE
No sounds heard 

### ISSUE THREAD

**Issue by birdtit** [hainguyents13/mechvibes#331]
I have a MacOs Sonoma 14.6 M1 and when I open the app it shows there is a JavaScript error. There are no sounds and the test button doesn't work. Does anyone know why this is happening? The older version I add before doesn't work either. 

<img width="260" alt="Screenshot 2024-08-02 at 3 00 51 PM" src="https://github.com/user-attachments/assets/160e0931-550c-4821-9b6d-ab00dc6cd46e">

**Comment by hainguyents13** [comment]
@birdtit how did you solve this?

**Comment by noopurphalak** [comment]
FYI, Version 2.3.2 works on mac os Sonoma
