### ISSUE TITLE
Fedora Linux: Appimage - Sound not playing when the app is minimalized.

### ISSUE THREAD

**Issue by theridev** [hainguyents13/mechvibes#333]
Keyboard sounds only work when you are on the app itself but when you minimalize the app the sound doesn't play on a keypress.

Version: 2.3.4

**Comment by manish-mehra** [comment]
@theridev same issue as well with fedora(40). even after allowing permission, sound not playing when app is minimized.
also fails when downloaded with snap package manager, but i have mentioned that in  here #320

**Comment by theridev** [comment]
Sorry for not updating, I solved the issue by logging out and switching to gnome on xorg (from Wayland).

Closing this.
