### ISSUE TITLE
Can't find editor on Mac 

### ISSUE THREAD

**Issue by flyboibyte** [hainguyents13/mechvibes#335]
Please help! I want to make my own custom keyboard sounds, but the editor is nowhere to be found! 
<img width="203" alt="Screenshot 2024-09-08 at 21 21 04" src="https://github.com/user-attachments/assets/0ff924c0-bbe1-4ff4-a44a-7b23de63f77b">
<img width="413" alt="Screenshot 2024-09-08 at 21 21 27" src="https://github.com/user-attachments/assets/2f550889-b4fb-4df2-a947-4e390b177bf3">
I'm using a MacBook Air on 14.6.1

**Comment by NotLazy** [comment]
Check the tray icon not the app icon. It's on the top right of your screen. If you can't see it you may need to close some other apps.
