### ISSUE TITLE
Unable to add Custom Sounds [2.3.0]

### ISSUE THREAD

**Issue by Chowtown** [hainguyents13/mechvibes#34]
Dragged copied folders into custom but when mechvibes opens, it shows a white screen

**Comment by hainguyents13** [comment]
try rename the custom sound folder to username-like name "nk-cream" or "regina-typewriter-1"

**Comment by Chowtown** [comment]
![image](https://user-images.githubusercontent.com/44385684/99452947-39b08b00-28f2-11eb-9590-943b6c994cac.png)
I've changed the custom sound folder names but nothing still appears

**Comment by TahirMurata** [comment]
Same I cant add the custom sound on the official website. I tried to Download NK Creme TaiHao Rubber by peppaplayz

**Comment by hainguyents13** [comment]
> Same I cant add the custom sound on the official website. I tried to Download NK Creme TaiHao Rubber by peppaplayz

try rename custom sound folder to "nk-cream-taihao" or something like that, and try again

**Comment by TahirMurata** [comment]
ok so I restarted my computer and mechavibes looks just like Chowtowns help

**Comment by alphamalegod69** [comment]
please help i have the same problem the more+ box just isnt there

**Comment by hainguyents13** [comment]
> please help i have the same problem the more+ box just isnt there

they are all moved to the system tray icon (on the bottom right of your screen)

**Comment by Chowtown** [comment]
Whenever I add a custom sound and I rename it to the way you mentioned (dashes for name) mechvibes just appear blank

**Comment by hainguyents13** [comment]
> Whenever I add a custom sound and I rename it to the way you mentioned (dashes for name) mechvibes just appear blank

can you show some picture of custom folder and mechvibes appear blank?

**Comment by Chowtown** [comment]
![image](https://user-images.githubusercontent.com/44385684/100390394-34dc8d00-2ffe-11eb-8ea7-be0788317b68.png)

**Comment by hainguyents13** [comment]
which folder did you copy sound folder to?

**Comment by Chowtown** [comment]
The custom folder that I get when I right click on the system tray icon

**Comment by Chowtown** [comment]
Any idea yet?

**Comment by TahirMurata** [comment]
@Chowtown I have the same problem

**Comment by Chowtown** [comment]
@TahirMurata yea, could you tell me when you find a solution? It's been 16 days. It's not like I'm dying to need it but it'd be pretty exciting if I can add those custom sounds you know.

**Comment by hainguyents13** [comment]
> @TahirMurata yea, could you tell me when you find a solution? It's been 16 days. It's not like I'm dying to need it but it'd be pretty exciting if I can add those custom sounds you know.

I cannot reproduce the error, can I contact you via twitter, facebook or google hangout for faster communication?

**Comment by Chowtown** [comment]
Oh of course that would be great! Do you have discord instead? I don't use many of the other platforms

**Comment by TahirMurata** [comment]
I haven't found a solution yet :/

**Comment by hainguyents13** [comment]
> I haven't found a solution yet :/

Im kinda busy now, please wait some days I will compile a new version with debug option

**Comment by Chowtown** [comment]
Any updates?

**Comment by byzocker** [comment]
I have the same issue! and i even reinstalled it
![image](https://user-images.githubusercontent.com/59401089/103955593-f1ba2180-5146-11eb-86f8-d32c42b76d40.png)

**Comment by asimo10** [comment]
> I have the same issue! and i even reinstalled it
> ![image](https://user-images.githubusercontent.com/59401089/103955593-f1ba2180-5146-11eb-86f8-d32c42b76d40.png)
> 
> and if you remove everything from the folder, it works again

I had the same thing and didn't know what to do. Now I know how to revert it, thanks!

**Comment by Chowtown** [comment]
Is there any solution to the custom sounds yet?

**Comment by kaijumydude** [comment]
Not a full solution but one way I found to get custom sound to work is to have only one custom sound in the mechvibes_custom folder at a time. Just keep your other sounds in a folder to the side and switch them out when you want to change the custom sound you're using. It's not very fun or as easy to not have them all available from the get go, but at least you'll be able to use them!

**Comment by Pigeonboi** [comment]
Also not sure what to do i downloaded a custom one and the "custom" tab doesn't show up in the app (windows 10)

**Comment by SubziCutter** [comment]
> ![image](https://user-images.githubusercontent.com/44385684/99452947-39b08b00-28f2-11eb-9590-943b6c994cac.png)
> I've changed the custom sound folder names but nothing still appears

yo fellas ive found the solution to this, so basically when you'll download a custom sound, you'll have a folder which has name of sound and creator most probably, then inside you'll have another folder with name of sound and in that folder you'll see your sound and a config file. what you have to do is cut and paste only the sound folder into custom sounds folder. if you put the complete downloaded folder in custom then you'll see the white screen like in above answers. You can also name that folder anything you like, no _ needed. I hope i was helpful!😄

**Comment by GraceRowel10** [comment]
So, I had the same problem, and I fixed it. All I had to do is to open my folder and search mechavibes_custom. I erased the sounds that I downloaded and restarted mechavibes. And Thank God, I can finally use the default sounds.

**Comment by JhonViz** [comment]
I already solved the problem, first close the mechvibes if you have it open, then go to this video ---> https://www.youtube.com/watch?v=dX6kVuiH1BM
And that's it, problem solved, I just did it and it works correctly, I hope it will be of much help to you, I had been with this problem for a week, now you can finally solve it, good luck friends 👌😎

**Comment by dawg112-wq** [comment]
i found the solution. So download any custom sound packs from the discord or wtv, now right click and click extract here. after that, u have to only put sounds packs that has the sounds only by double clicking it. if it has files or other and not sounds then u cant put it in. If u have any problems with it, js tell me

**Comment by Kostas865** [comment]
> i found the solution. So download any custom sound packs from the discord or wtv, now right click and click extract here. after that, u have to only put sounds packs that has the sounds only by double clicking it. if it has files or other and not sounds then u cant put it in. If u have any problems with it, js tell me

I cannot do it. I am trying many days now .
I choosed a typewriter sound, it sent to download files. Then i extract file to custom folder. I open the app but the custom sound doesn't appear...

**Comment by Kostas865** [comment]
> > I haven't found a solution yet :/
> 
> Im kinda busy now, please wait some days I will compile a new version with debug option

I cannot do it. I am trying many days now .
I choosed a typewriter sound, it sent to download files. Then i extract file to custom folder. I open the app but the custom sound doesn't appear...

**Comment by Kostas865** [comment]
> Same I cant add the custom sound on the official website. I tried to Download NK Creme TaiHao Rubber by peppaplayz

**Comment by Kostas865** [comment]
Did you find any solution?I cannot do it. I am trying many days now .
I choosed a typewriter sound, it sent to download files. Then i extract file to custom folder. I open the app but the custom sound doesn't appear...
