### ISSUE TITLE
No sounds are played on MacOS Sequoia

### ISSUE THREAD

**Issue by tiagorangel1** [hainguyents13/mechvibes#357]
The app opens correctly after me allowing it from Settings, but keyboard sounds are not played. Even with both app volume and system-wide volume at max, no sound is getting played.

Yeah, I've granted accessibility permissions.

![28451](https://github.com/user-attachments/assets/1d6020ef-e0f2-4aa0-bf06-600223ef7d63)

**Comment by tiagorangel1** [comment]
Processes running:

![72826](https://github.com/user-attachments/assets/73a1bc2d-8ba6-4b96-8e67-6d73f929c235)

**Comment by NotLazy** [comment]
If you've previously used v2.3.1 or earlier on your mac, ensure you remove mechvibes from your accessibility permissions, and re-add it back. Ensure Mechvibes is fully closed while you remove and re-add it.

If you're unsure how, Go to your system settings and navigate to **Privacy & Security** > **Accessibility** and click on **Mechvibes** then click the – icon towards the bottom of the window. 

In my testing, macOS rejects the attempt Mechvibes makes to re-add the app to accessibility permissions, so you'll need to click the + icon, and find your currently installed Mechvibes.app file. YMMV though, so feel free to test if it gets re-added automatically for you.

If this doesn't work for you, let me know and i'll re-open this issue.

**Comment by tiagorangel1** [comment]
I don't think that was the issue since I had already given permission but when reinstalling it fixed it. Didn't even need to give permission again.
