### ISSUE TITLE
not loading

### ISSUE THREAD

**Issue by LeeWasntTaken** [hainguyents13/mechvibes#37]
its not loading help

**Comment by hainguyents13** [comment]
check FAQ or specify your problem

**Comment by rosecookieYT** [comment]
its not loading i have been waiting for an hour

**Comment by hainguyents13** [comment]
> its not loading i have been waiting for an hour

it shows "loading"?

**Comment by HolyTapestry** [comment]
help me it says loading and dosent load please help meee

**Comment by HolyTapestry** [comment]
i cant even  check FAQ

**Comment by Anto3733** [comment]
> > its not loading i have been waiting for an hour
> 
> it shows "loading"?

yes, do you have a fic for it?

**Comment by hainguyents13** [comment]
check this first https://mechvibes.com/faqs/

**Comment by Anto3733** [comment]
nope it didnt lead to anything
