### ISSUE TITLE
How to run off of source code

### ISSUE THREAD

**Issue by amirarshia** [hainguyents13/mechvibes#42]
Hello, I wanted to know how I should run it off of the source code.

**Comment by hainguyents13** [comment]
you should install nodejs, clone the repo, install dependencies then run
"npm start"

**Comment by amirarshia** [comment]
Ok, I will try that.

**Comment by amirarshia** [comment]
Can I ask what the dependencies are?

**Comment by amirarshia** [comment]
Never mind I found the dependencies, thanks for your help!
