### ISSUE TITLE
Character encoding

### ISSUE THREAD

**Issue by kosirm** [hainguyents13/mechvibes#44]
Hi,
This is amazing app, I'm using it constantly from the moment I found it.
Thank you so much for creating this app and sharing it for free with the community!

I would like to use Unicode characters for Croatian language (čćšđž), is it possible?

Thanks for any reply!

**Comment by hainguyents13** [comment]
thanks but I dont get your point, unicode characters for what?

**Comment by kosirm** [comment]
Sorry for my stupid question! I have a Croatian keyboard... so I will just use English equivalents for keys... Please forget about this :smile:

**Comment by kosirm** [comment]
Ok, I will reopen this... because if I set English letters and then switch to my Croatian keyboard (windows - language preferences), some key's are not working, even if I set them correctly. It would be great if I could use ISO 8859-2 encoding, which has support for Croatian language specific characters (čćšđž). Is it possible maybe?

**Comment by hainguyents13** [comment]
not sure about that since I only work with the keycodes of the keyboard, not the language

**Comment by kosirm** [comment]
Thanks, 
JavaScript has great support for various encodings... for example [iso-8859-2](https://www.npmjs.com/package/iso-8859-2). As far as I know, also UTF-8 would be ok. Just an idea... maybe it could be configurable with keycodes.js... I know it's additional work, but if you want me to test here on my Croatian keyboard, I would be glad to do it.
