### ISSUE TITLE
White bar and install problems

### ISSUE THREAD

**Issue by jay78x** [hainguyents13/mechvibes#46]
I had the white bar problem and I couldn't fix it after restarting the my computer so I unistalled mechvibes and every folder with it but for some reason when I try and reinstall it, I can only get it to install about 1/3 of the way on the bar and it just stops. I have been letting it try to download for over and hour.

**Comment by marigisee** [comment]
I have the same problem

**Comment by marigisee** [comment]
hey! i joined the discord server. i asked there and they answered me and now it works fine. i suggest you to do the same!
