### ISSUE TITLE
Doesn't work on numeric pad

### ISSUE THREAD

**Issue by haseebchowdhury** [hainguyents13/mechvibes#5]
Hello developer, I really loved your work. Everything's fine, but the numbers on the numeric pad (on the right side of the typical keyboards) don't make sound. I think it is a limitation of this software. Typical laptop users won't find a issue who don't have a numeric pad on their keyboard. I kindly request the developer of this software to add sounds to the numeric keypad. Then it will be more gorgeous. Thank you.

**Comment by andika207** [comment]
@haseebchowdhury 
-make sure the neon led ''Num Lock'' is off 
-click on **Bloq Num** key in order to disable it.

**Comment by andika207** [comment]
@haseebchowdhury
-make sure the neon led ''Num Lock'' is off
-click on ''Bloq Num'' key in order to turn it off

**Comment by andika207** [comment]
@haseebchowdhury 
-make sure the neon led ''Num Lock'' is off
-click on ''Bloq Num'' key in order to turn it off
-on my keyboard some keys never make sound: >>>> bloq num, 5, /, -, *, +, enter,

**Comment by andika207** [comment]
@haseebchowdhury
-make sure the neon led ''Num Lock'' is off
-click ''Num Lock'' key in order to turn it off
-on my keyboard some keys never make sound: >>>> bloq num, 5, /, -, *, +, enter,

**Comment by andika207** [comment]
@haseebchowdhury
-make sure the neon led ''Num Lock'' is off
-click ''Num Lock'' key in order to turn it off
-on my keyboard some keys never make sound: >>>> numlock, 5, /, -, *, +, enter,

**Comment by hainguyents13** [comment]
@haseebchowdhury hi, official sound packs currently dont support numpad keys. 
I will create custom packs with numpad keys added then you can add to Mechvibes yourself.

**Comment by andika207** [comment]
@hainguyents13 numeric pad.

**Comment by haseebchowdhury** [comment]
@hainguyents13 Alright. Thank you so much for your kind response.

**Comment by hainguyents13** [comment]
@haseebchowdhury I uploaded a new version with some changes including numeric support, check it out in Releases or https://mechvibes.com

**Comment by haseebchowdhury** [comment]
> @haseebchowdhury I uploaded a new version with some changes including numeric support, check it out in Releases or https://mechvibes.com

OMG bro. Thank you soo sooo much. And thanks for letting me know this here. Appreciated. I've already updated the program and this is perfect now.

**Comment by hainguyents13** [comment]
@haseebchowdhury you are welcome bro! If there is any problem in using this app, please let me know, always here to help
