### ISSUE TITLE
(Suggestion) - adding option to randomize sound everytime the mechvibes open

### ISSUE THREAD

**Issue by FajarMaftuhFadli** [hainguyents13/mechvibes#52]
So, this option can make mechvibes randomly picking the sound from installed sound package (or chosen package) every time the mechvibes opened. Great app btw ♥️♥️♥️

**Comment by DaniilVysotskiy** [comment]
Would be just great to have randomly picked sound set for me each time I start new working day.

**Comment by DaniilVysotskiy** [comment]
Add pull request - https://github.com/hainguyents13/mechvibes/pull/195

**Comment by NotLazy** [comment]
#195 has been implemented as well as #251 which provides a fix, and #252 which rewrites it for an optimization update.
