### ISSUE TITLE
Does Not Work With Visual Studio Code

### ISSUE THREAD

**Issue by thousandtyone** [hainguyents13/mechvibes#53]
Downloaded the program and installed it. Works flawlessly everywhere else but simply stops working in visual studio code. Once in visual studio code no sounds are produced. Any one else having the same issue?

**Comment by thousandtyone** [comment]
Correction: I am working with a terminal emulator (cmder). When start visual studio code from the emulator / terminal by typing "code" Mechvibes doesn't work. However when I start it from the command prompt it works just fine.

**Comment by hainguyents13** [comment]
try open Mechvibes as Admin, I think it will work as you want

**Comment by thousandtyone** [comment]
That did the trick. It worked. Able to get the sounds now. Awesome, Thanks so much for your help with this!
