### ISSUE TITLE
AltGr key on Windows playing the sound while being held down

### ISSUE THREAD

**Issue by lilspelunker** [hainguyents13/mechvibes#54]
When on Windows (only tested on Windows 8.1), if you hold down the AltGr key it will play the sound for keypress repeatedly untill you stop pressing the key (unlike the other keys playing it once even if you hold it down).

**Comment by Dubhghall** [comment]
LOL

**Comment by nhamtphat** [comment]
Me too, it will be repeated when pressing Shift+Alt
