### ISSUE TITLE
Greate app man.

### ISSUE THREAD

**Issue by MonirHosain** [hainguyents13/mechvibes#56]
Really It's a Greate app. when I record my youtube video I can't remove my keyboard sound. If  I record audio after screen recording, I cant add keyboard sound. But It's a great app for adding keyboard sound like a system sound in my videos. Thanks for this awesome application.

#One issue I found that with clicking Shift + (others Key), Sometimes It gives double sound.

**My Gift**
```javascript
var x= 6.02 * 10**23;

for (let i = 0; i < 2*x; i++) {

document.write("Love <3"+"<br>");


};
```

**Comment by hainguyents13** [comment]
thank you, man! I have been reported about that issue before but still dont know how to reproduce the issue, I will try my best to fix it soon

**Comment by max-programming** [comment]
> Really It's a Greate app. when I record my youtube video I can't remove my keyboard sound. If I record audio after screen recording, I cant add keyboard sound. But It's a great app for adding keyboard sound like a system sound in my videos. Thanks for this awesome application.
> 
> #One issue I found that with clicking Shift + (others Key), Sometimes It gives double sound.
> 
> **My Gift**
> 
> ```js
> var x= 6.02 * 10**23;
> 
> for (let i = 0; i < 2*x; i++) {
> 
> document.write("Love <3"+"<br>");
> 
> 
> };
> ```

If your screen recorder also recording the system sound, then it will record the keyboard sound too
