### ISSUE TITLE
Not working on VS Code Windows 10

### ISSUE THREAD

**Issue by Badrouu17** [hainguyents13/mechvibes#6]
Working great on any windows 10 app except vs code, any specific configuration !?

**Comment by hainguyents13** [comment]
I use Mechvibes along with VSCode too and it works fine so I can't reproduce the error.
You can try to run this app as administrator and see if it work

**Comment by Badrouu17** [comment]
Worked! Thanks, and good job by the way 👏👏👏 this app is awesome

**Comment by hainguyents13** [comment]
thanks! glad it helps
