### ISSUE TITLE
After a while of use these are my thoughts

### ISSUE THREAD

**Issue by G3NSVRV** [hainguyents13/mechvibes#61]
I think the app is great, is fast, does not get stuck when you typing, everything works perfectly, but... this app consumes some memory and would be great if can consume less. This is the current state on fresh start:

![2021-02-03_09h04_55](https://user-images.githubusercontent.com/11720535/106758884-d0970480-6610-11eb-88f4-97b32365a5f7.png)

After a while this raises to consumes around ~500mb memory.

**Comment by l3afblow3r** [comment]
Just wanted to write the same.
The application is awesome and works flawlessly.

It's just unacceptable that it uses this much memory
for something that just intercepts key presses and plays sounds.

**Comment by NotLazy** [comment]
Fixed in #252
