### ISSUE TITLE
Mechvibes slowing down my computer

### ISSUE THREAD

**Issue by Miguelsanchezzz** [hainguyents13/mechvibes#62]
hey, so i installed mechvibes in my computer and when i open it it just slows down everything really slow, makes it imposible to move the mouse or to type, besides no sound coming out. I have a decent computer, not very powerfull but runs games like valorant or league and WoW so i wonder what's the problem. Ive unistalled and installed it again but still same problem.
If anyone can help me i would appreciate it.
Thx

**Comment by NotLazy** [comment]
I'm going to close this issue due to inactivity but if you're still facing this issue, feel free to reach out on our discord.
