### ISSUE TITLE
Unable to upload custom sounds (v2.3.0)

### ISSUE THREAD

**Issue by Emikuma** [hainguyents13/mechvibes#63]
I've followed some of the other tutorials here on the forums, as well as on the site, but I'm still unable to add the custom sound to the app. I'm unsure what I'm doing incorrectly, or if there is an issue with the custom folders I'm just not seeing? 

Help is appreciated!!

**Comment by akira-yasha** [comment]
I don't kow if your issue is still relevant, but I have some other sources available for you

> On Windows
>  ›  Download a soundpack
>  ›  Right-click the zipped file > Extract
>  ›  Go to the bottom right > Locate the :systray: and click it
>  ›  Right-click the :Mechvibes: > 'Custom Folder'
>  ›  Copy or drag the unzipped folder in to your 'custom' folder
>  ›  Restart Mechvibes.
> On Mac
>  ›  Download a soundpack
>  ›  Double click the zipped file to extract it
>  ›  Go to the top right > Right-click the :Mechvibes:
> ⠀'Show package content'
>  ›  Make a new folder called 'custom'
>  ›  Copy or drag the unzipped folder in to your 'custom' folder
>  ›  Restart Mechvibes.
> ###### Taken from our [Discord](https://discord.gg/59mBvvbXkj)

and there is [this video](https://www.youtube.com/watch?v=ekoKZ3wMHt8) i've made to show how to do it visually.
