### ISSUE TITLE
Sound only works in application using Chrome OS Linux beta

### ISSUE THREAD

**Issue by roteli** [hainguyents13/mechvibes#64]
I don't know if this just doesn't work on Chrome, but I was able to install mechvibes through Linux beta and thought it was great!  

...Until I realized that the sounds only work when I am on the application itself :/  

When I move to another app or tab the sound does not work. Did I mess up when installing, or is there just something I am overlooking? Any help would be appreciated!

**Comment by CaptainObnoxious** [comment]
In my experience, it's a problem exclusive to google chrome so far. In my case all letter and number keys do not play the sound while google chrome is the window I'm focused on. Special characters that are on their own keys, such as period and comma seem to work fine, as well as most of the others. Arrow keys, space bar, shift, control, alt, enter, backspace etc. all function properly. I'm also positive it's not chromium based, but exclusive to chrome, as it works in Discord and Steam.
