### ISSUE TITLE
Official Release includes a bunch of joke/meme sounds

### ISSUE THREAD

**Issue by mimshwright** [hainguyents13/mechvibes#68]
I just did a fresh install (v.2.3.0) that I got from https://github.com/hainguyents13/mechvibes/releases/tag/v2.3.0

The package includes a bunch of non-keyboard sounds. Some are inappropriate/offensive (anime moan, sexy voice), some are super annoying (sound warning), some are both (I ain't never seen to pretty best friends). 

I understand that some people enjoy these kinds of sound packs (probably nobody wants the annoying ones) but for an app that requests system-level access, it's very disappointing and annoying to have to reset the app because I got rickrolled.

I request that you only include pleasant / keyboard sounds in your official release.

**Comment by hainguyents13** [comment]
sir that's totally my fault! I added them for testing and forgot to delete them on compiling. Thanks for pointing that out!

**Comment by thecashewtrader** [comment]
> sir that's totally my fault! I added them for testing and forgot to delete them on compiling. Thanks for pointing that out!

Uhm
It still doesnt seem to be fixed 😅

**Comment by EricPlayZ** [comment]
> > sir that's totally my fault! I added them for testing and forgot to delete them on compiling. Thanks for pointing that out!
> 
> Uhm
> It still doesnt seem to be fixed 😅

It is. Did you update the app?

**Comment by thecashewtrader** [comment]
> > Uhm
> > It still doesnt seem to be fixed sweat_smile
> 
> It is. Did you update the app?

I did.
I am using v2.30 AppImage on Arch Linux

**Comment by sudhamjayanthi** [comment]
this. still got rickrolled twice 😤

**Comment by NotLazy** [comment]
This will *for sure* be resolved in v2.3.2 and might already be resolved in v2.3.1
