### ISSUE TITLE
Does the portable version 2.1.1 support custom folders?

### ISSUE THREAD

**Issue by UNIVAC-Colonel-Panic** [hainguyents13/mechvibes#7]
I downloaded and unzipped `custom - man-voice.zip`, then launch the portable .exe.

I've tried:
* click on +More->Open Custom Folder. This just launches a new instance of File Explorer pointing to `%localappdata%\Temp\randomfoldername`. There's no folder/file picker.
* click on +More->Open Editor->Browse custom packs. This doesn't open a folder/file picker either but blinks the Editor on/off briefly.
* click on +More->Open Editor->Editing existing pack: This _does_ open a folder/file picker. I navigate to the extracted `custom - man-voice\demo-define-by-file-name\config.json` and open it. I don't make any changes since I just want to try the demo pack. I don't export config.json since it already exists, and the custom folder `custom - man-voice\demo-define-by-file-name` already exists so no folder copying seems to be needed.

If I launch the Editor and go to Help, all the choices there are about Electron.

If the portable version isn't meant to work with custom packs, I'll understand, but I'm not seeing any documentation that describes this limitation.

What am I doing wrong?

**Comment by hainguyents13** [comment]
hi there,
yes there the limitation of the portable version, sorry for not mentioning it in the doc

**Comment by POTSandSTOP** [comment]
Thanks for getting back to me. No problem, I'll switch to the full version.

**Comment by POTSandSTOP** [comment]
On second thought, before I close this out for good, would you be able to disable the custom folder functions in the portable version? Then people like me, when not running on much sleep, won't be tempted to even try it.. 😄

**Comment by hainguyents13** [comment]
thanks for reminding, so I will close this myself after updating it just in case I forget
