### ISSUE TITLE
stuck on installing ;-;

### ISSUE THREAD

**Issue by aemilk** [hainguyents13/mechvibes#78]
well i reinstalled it after no options now its stuck on installing ;-;
![image](https://user-images.githubusercontent.com/41359534/114444407-c3753380-9bc6-11eb-9b83-dcaa0c2960f0.png)

what to do?

**Comment by l3afblow3r** [comment]
Open `%appdata%/Mechvibes` and delete everything inside it.

**Comment by aemilk** [comment]
I managed to clear but now it gives an error:
![image](https://user-images.githubusercontent.com/41359534/114704808-ed416e00-9d1e-11eb-8b43-56ecc58e1f86.png)
I chose my hard drive but it still didnt work.

**Comment by l3afblow3r** [comment]
Does 2.3.0 work for you?

**Comment by aemilk** [comment]
I uninstalled it from Control Panel now i can install.

But thanks for helping!
