### ISSUE TITLE
Mechvibes didn't work on Kubuntu 18.04

### ISSUE THREAD

**Issue by dinhbaovuong** [hainguyents13/mechvibes#8]
I installed mechvibes with "sudo snap install mechvibes" (completed).
But when I launch it, the "button" is "loading" and the drop-down list of switchs and keycaps is unable.
How can I fix it?

**Comment by hainguyents13** [comment]
hey mate, 
I don't have any machine running Kubuntu so I cannot reproduce the problem now, I will install a virtual machine with Kubuntu to test it and let you know asap. 
in the meantime, you can try the deb version and see if it work.

**Comment by dinhbaovuong** [comment]
> hey mate,
> I don't have any machine running Kubuntu so I cannot reproduce the problem now, I will install a virtual machine with Kubuntu to test it and let you know asap.
> in the meantime, you can try the deb version and see if it work.

I tried install with deb file but it gave the same result :((
It works well on windows 10 in the same laptop btw.

**Comment by dopedotcode** [comment]
Same issue on Fedora 32

**Comment by mango10k** [comment]
same issue on Arch Linux

**Comment by anhnicky66** [comment]
@dopedotcode @mrmango1  Try to run AppImage file with `--no-sandbox` parameter
```
./Mechvibes-2.3.0.AppImage --no-sandbox
```

**Comment by somethingiswrongz** [comment]
@anhnicky66 Thanks mate
