### ISSUE TITLE
Do not work on the OBS window

### ISSUE THREAD

**Issue by Rubylium** [hainguyents13/mechvibes#80]
I noticed that when the OBS window is in focus, no sound are being played.

**Comment by yasons** [comment]
I recommend you to use VoiceMeeter Banana, and make OBS capture the sound from VoiceMeeter Ouput.
Try to find out the tutorial in Youtube about using VoiceMeeter.
I'm an elementary teacher and find this VoiceMeeter is beyond helpful.
