### ISSUE TITLE
Not working well since I switch to wayland (Ubuntu 21.04)

### ISSUE THREAD

**Issue by AnnaTartine** [hainguyents13/mechvibes#86]
Hi, i noticed that since the update with wayland by default (instead of Xorg) mechvibes does not work most of the time. It's work only with some software on focus, like Discord, but not with LibreOffice, Firefox etc.. 

I hope the problem is not with my system. I tried both appimage and .deb. I can still use Xorg for the moment. I do understand it's not the most urgent issue, but I wanted to help a little by pulling this issue

Mechvibe is great for me on my laptop, thanks for the good work !

**Comment by Technohacker** [comment]
From my testing it's only Wayland native applications that don't make a sound. Mechvibes and the others that do, all use X11 for GUI, hence why keystrokes from X11 applications are accessible to other X11 applications. I believe Wayland's input model is slightly more restrictive, hence there may need to be a different way of requesting keystrokes

One option is to bind to libinput directly, which does require direct access to the device nodes and thus, elevated access for the program. Could be a security risk, but it sounds like a workable option for now :)

**Comment by Technohacker** [comment]
I made a very hacky fix that makes it work on Wayland for all apps, but it required root access to access the input devices directly. I took [this project](https://github.com/AlynxZhou/showmethekey)'s CLI companion, hooked it up to the input system the program uses, and it worked :)

I'm pretty sure Wayland will implement some form of permissions system later on, but for now this could be the only method that's workable

**Comment by AnnaTartine** [comment]
Thanks a lot for the answer ! Being not the most experienced linux user I was sticking for Xorg for the moment. I may try the solution you found, thanks a lot for the help i really appreciate

Wayland cause me few problems other than mechvibes, but I'm aware that Wayland is still on a process to get better and better and I glad to here that you optimistic about permissions on Wayland, I'll stay aware of what happen

I will try to reach out here if I see somethings related to this issue, as I can think other Linux user might be interested !

Thanks for the answer have a great day/night !

**Comment by NoEnd-yt** [comment]
> I made a very hacky fix that makes it work on Wayland for all apps, but it required root access to access the input devices directly. I took [this project](https://github.com/AlynxZhou/showmethekey)'s CLI companion, hooked it up to the input system the program uses, and it worked :)
> 
> I'm pretty sure Wayland will implement some form of permissions system later on, but for now this could be the only method that's workable

I have this problem too, so how did you fix it? Can you make a step-by-step tutorial?

**Comment by thiagojack** [comment]
> I made a very hacky fix that makes it work on Wayland for all apps, but it required root access to access the input devices directly. I took [this project](https://github.com/AlynxZhou/showmethekey)'s CLI companion, hooked it up to the input system the program uses, and it worked :)
> 
> I'm pretty sure Wayland will implement some form of permissions system later on, but for now this could be the only method that's workable

@Technohacker how did you do it?
