### ISSUE TITLE
Can't add custom sounds in Mac OS

### ISSUE THREAD

**Issue by grand1k7** [hainguyents13/mechvibes#9]
I can't find the custom folder, and when I click open custom folder nothing happens? I am currently running Mac OS Mojave.

**Comment by hainguyents13** [comment]
sorry but I dont have any machine running macos right now, I will install a virtual machine to test it and let you know asap

**Comment by grand1k7** [comment]
Thanks, will await your response

**Comment by The-Danx** [comment]
For anyone else on MacOS you put the custom folder in the "Show Package Contents" of the application

**Comment by MrGodlyZeus** [comment]
When I open that folder it shows a folder called contents do I put it inside of that?

**Comment by hainguyents13** [comment]
> When I open that folder it shows a folder called contents do I put it inside of that?

you are using the old verson of Mechvibes, you should create a folder name "custom" and put downloaded sounds into it
