### ISSUE TITLE
Feature Request 

### ISSUE THREAD

**Issue by demonite87x** [hainguyents13/mechvibes#91]
your program is good but its kinda unrealistic since when you hold the key it plays the sound of you unpressing it even tho im still holding the key, so can you a make it detect when the key that pressed is being hold, make the unclick sound not play until i release the key, if thats impossible to make then its fine.

**Comment by PyroCalzone** [comment]
Please check out MechvibesPlusPlus for this feature. <3

**Comment by demonite87x** [comment]
can you link it?
