### ISSUE TITLE
No sound on macos big sur

### ISSUE THREAD

**Issue by phildev4** [hainguyents13/mechvibes#95]
No sound is played if I press a button.
However, It detects that a key input is pressed. Please fix

Macos big sure 11.2.1
MacBook Air (13-inch, 2017)

YES, I read the FAQ
Just wanted to point that out

**Comment by phildev4** [comment]
YES, I read the FAQ
Just wanted to point that out

**Comment by phildev4** [comment]
Just delete the mechvibes folder in the libary folder.

**Comment by ElizabethRen** [comment]
When you open your system preferences, go to security and privacy > accessibility. Remove Mechvibes from the list and then add it back again. Grant access again quit mechvibes and then right-click to open the app again. It should be working by then. 

Hope this helps!

**Comment by phildev4** [comment]
Deleting the mechvibes and running the app from source helped for me. I assume deleting the mechvibes folder from the Libary folder works, however, running the electron source instead of the binary also might have helped idk. However, thank you for your response!

**Comment by Paraslaul** [comment]
Still no sound for me i did everything you told multiple times.

**Comment by phildev4** [comment]
I am sorry to hear that! However, I didn't code this and so I can't help you

**Comment by aguy1111** [comment]
If anyone has the same issue, quit the app from the top right then reopen it. It worked fine for me
<img width="143" alt="Screen Shot 2022-03-15 at 11 24 57 AM" src="https://user-images.githubusercontent.com/101628693/158336237-b2c0ae7f-1b32-4577-9013-881996103578.png">
.

**Comment by Brute-Coder** [comment]
thank you so much for the help

**Comment by MaticAlgos** [comment]
Tried everything from here, eventually force reload worked for me. Thank you!

<img width="491" height="239" alt="Image" src="https://github.com/user-attachments/assets/60390017-29d2-4ea7-b4df-d1dca591cfcb" />
