### ISSUE TITLE
[Suggestion] Release key sounds

### ISSUE THREAD

**Issue by Xoverse** [hainguyents13/mechvibes#96]
Hi, this is more a suggestion, but,
the sounds are press and release, and it is fully played when the key is pressed.
The effect works nice, but if we hold a key, the release sound, that is in the MP3 with the press, is heared too.
The press and release sounds should be separated, so when we hold keys, we don't hear the release sound while the key is always pressed.

**Comment by NotLazy** [comment]
#21
